### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by demiantres** [kewlbear/FFmpeg-iOS-build-script#100]
When running the vanilla build-ffmpeg.sh script I am always gettings this error:

``

 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/libavcodec/aarch64/h264dsp_init_aarch64.c:90:40: warning: incompatible
      pointer types assigning to 'h264_biweight_func' (aka 'void (*)(unsigned
      char *, unsigned char *, long, int, int, int, int, int)') from 'void
      (uint8_t *, uint8_t *, int, int, int, int, int, int)' (aka 'void (unsigned
      char *, unsigned char *, int, int, int, int, int, int)')
      [-Wincompatible-pointer-types]
        c->biweight_h264_pixels_tab[2] = ff_biweight_h264_pixels_4_neon;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings generated.
CC	libavcodec/aarch64/h264pred_init.o
AS	libavcodec/aarch64/h264pred_neon.o
src/libavutil/aarch64/asm.S:74:2: error: unexpected token at start of statement
 # //.size p16weight, . - p16weight
 ^
make: *** [libavcodec/aarch64/h264pred_neon.o] Error 1
make: *** Waiting for unfinished jobs....
``

**Comment by demiantres** [comment]
``--disable-asm`` fixes the problem.

**Comment by kewlbear** [comment]
Please retry after finding and deleting all `gas-preprocessor.pl`.

**Comment by intveltr** [comment]
I got the same error. 

After commenting out AS="gas-preprocessor..." in the build script (forcing AS="$CC"), the compiler gets a little bit further until it hits libavcodec/aarch64/simple_idct_neon.o with a bunch of "invalid operand" errors.

It did compile with the --disable-asm flag.

**Comment by ZekeLee** [comment]
作者用的是这个项目的perl文件
https://github.com/libav/gas-preprocessor
一定要看清楚，github上有好多gas-preprocessor项目
