### ISSUE TITLE
FFMPEG binary for iOS - no bitcode symbol found 

### ISSUE THREAD

**Issue by NishantSharmIndia** [kewlbear/FFmpeg-iOS-build-script#102]
These ffmpeg lib binaries does not support bit code and because of that our iOS project need to disable bitcode which disable generation of dsym which are useful for analysing market crash iOS issue.

Please support it - "-fember-bitcode" flag need to add while building all libs.

To verify whether it contain bit code or not use oTool command

**Comment by kewlbear** [comment]
Actually this script already support bitcode. See https://github.com/kewlbear/FFmpeg-iOS-build-script/blob/master/build-ffmpeg.sh#L99. You need to specify architecture for devices when running `otool`. See https://stackoverflow.com/a/33105733/2570853.
