### ISSUE TITLE
Linking Libraries

### ISSUE THREAD

**Issue by WilsonCP** [kewlbear/FFmpeg-iOS-build-script#105]
I've encountered this error when invoking av_register_all(). I'm on swift and already has a bridging header.

> Undefined symbols for architecture arm64:
  "_VTCompressionSessionGetPixelBufferPool", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_VTCompressionSessionEncodeFrame", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_VTCompressionSessionCreate", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_AverageBitRate", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_ProfileLevel", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_MaxKeyFrameInterval", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_MoreFramesAfterEnd", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_PixelAspectRatio", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_TransferFunction", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_ColorPrimaries", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_4_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_CMVideoFormatDescriptionGetH264ParameterSetAtIndex", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _get_params_size in libavcodec.a(videotoolboxenc.o)
      _copy_param_sets in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetFormatDescription", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_output_callback in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetTotalSampleSize", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_kCMTimeInvalid", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetDataBuffer", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_AudioFormatGetPropertyInfo", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
  "_CMSampleBufferGetPresentationTimeStamp", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetSampleAttachmentsArray", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_DataRateLimits", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms", referenced from:
      _av_videotoolbox_default_init2 in libavcodec.a(videotoolbox.o)
  "_CMSampleBufferGetDecodeTimeStamp", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_1_3", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_3_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_4_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_3_2", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_High_5_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_3_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_CMTimeMake", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_MoreFramesBeforeStart", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_VTSessionSetProperty", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_4_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_AllowFrameReordering", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kCMSampleAttachmentKey_NotSync", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_3_2", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_5_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_AudioConverterDispose", referenced from:
      _ffat_close_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_close_encoder in libavcodec.a(audiotoolboxenc.o)
  "_kCMTimeIndefinite", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_close in libavcodec.a(videotoolboxenc.o)
  "_CMBlockBufferCopyDataBytes", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_AudioConverterSetProperty", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterNew", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_VTDecompressionSessionWaitForAsynchronousFrames", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_VTCompressionSessionCompleteFrames", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_close in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_3_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_CMBlockBufferCreateWithMemoryBlock", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_CMSampleBufferCreate", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionDecodeFrame", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_AudioConverterGetProperty", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_VTDecompressionSessionInvalidate", referenced from:
      _av_videotoolbox_default_free in libavcodec.a(videotoolbox.o)
  "_kVTProfileLevel_H264_Main_3_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_CMVideoFormatDescriptionCreate", referenced from:
      _av_videotoolbox_default_init2 in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionCreate", referenced from:
      _av_videotoolbox_default_init2 in libavcodec.a(videotoolbox.o)
  "_kVTCompressionPropertyKey_YCbCrMatrix", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_AudioConverterGetPropertyInfo", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_kVTEncodeFrameOptionKey_ForceKeyFrame", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_AudioFormatGetProperty", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
  "_VTCompressionSessionPrepareToEncodeFrames", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_VTSessionCopyProperty", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_AudioConverterReset", referenced from:
      _ffat_decode_flush in libavcodec.a(audiotoolboxdec.o)
      _ffat_encode_flush in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterFillComplexBuffer", referenced from:
      _ffat_decode in libavcodec.a(audiotoolboxdec.o)
      _ffat_encode in libavcodec.a(audiotoolboxenc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

libz, libbz2, libiconv.tbd has already been added on Link Binaries. Thanks!

**Comment by kewlbear** [comment]
"VT" prefix stands for VideoToolbox, so link against VideoToolbox.framwork.
