### ISSUE TITLE
how can i use ffmpeg with x265

### ISSUE THREAD

**Issue by hsumen** [kewlbear/FFmpeg-iOS-build-script#106]
x265 compile finish.

add to "fat-265" folder
fat-265/include/x265_config.h 
fat-265/include/x265.h
fat-265/lib/libx265.a

change script

`X265=`pwd`/fat-x265

if [ "$X265" ]
then
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-gpl --enable-libx265"
fi

if [ "$X265" ]
        then
        CFLAGS="$CFLAGS -I$X265/include"
        LDFLAGS="$LDFLAGS -L$X265/lib"
        fi
`
but,
building arm64...
ERROR: x265 not found using pkg-config

what happen ? How can i do?

**Comment by kewlbear** [comment]
Make sure you built x265 for iOS. Edit the script to set `X265` to the build output directory of x265. You should not copy/move any files.

**Comment by hsumen** [comment]
https://github.com/hsumen/iostest/blob/master/build-ffmpeg.sh

**Comment by hsumen** [comment]
i try again.
but same error "ERROR: x265 not found using pkg-config"
Can you check my changed script?
https://github.com/hsumen/iostest/blob/master/build-ffmpeg.sh
i have no idea to fix it.
