### ISSUE TITLE
the problem "GNU assembler not found, install/update gas-preprocessor"

### ISSUE THREAD

**Issue by acekiller** [kewlbear/FFmpeg-iOS-build-script#108]
I have the same problem, when complie the FFmpeg. and the gas-preprocessor is auto download when runing the script. and the issue: https://github.com/kewlbear/FFmpeg-iOS-build-script/issues/20 is not enable.
[config.log](https://github.com/kewlbear/FFmpeg-iOS-build-script/files/1364424/config.log)

**Comment by acekiller** [comment]
OK, thinks! The problem is the location /opt/local/bin/gas-preprocessor.pl need update.

**Comment by cmeng-git** [comment]
see https://ffmpeg.org/pipermail/ffmpeg-user/2016-January/030202.html
