### ISSUE TITLE
ios执行脚本失败

### ISSUE THREAD

**Issue by 18911131970** [kewlbear/FFmpeg-iOS-build-script#111]
building arm64...
xcrun -sdk iphoneos clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

下载的最新版本 
xcode9.0

**Comment by kewlbear** [comment]
Please write in English. Try again after running `xcode-select --install` in terminal.

**Comment by BossKing** [comment]
i use this shell with Xcode8.3.3 is OK just now
老铁 我建议你先使用Xcode8.3.3 试试 排除Xcode版本问题
