### ISSUE TITLE
Undefined symbols in architecture x86_64/arm64

### ISSUE THREAD

**Issue by ashutosh-samosa** [kewlbear/FFmpeg-iOS-build-script#112]
Hello,
I get this Linker Error while building for simulator or device.
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FFBitstreamFilter", referenced from:
      objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
  "_OBJC_CLASS_$_FFOutputFile", referenced from:
      objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
  "_OBJC_CLASS_$_FFInputFile", referenced from:
      objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
  "_OBJC_CLASS_$_FFOutputStream", referenced from:
      objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have added the following frameworks & libraries
CoreMedia, VideoToolbox, libbz2, libbz, libiconv, libFFmpegWrapper.a

Any ideas where I'm going wrong?

**Comment by kewlbear** [comment]
I suspect library search path error regarding libFFmpegWrapper.a.  But it's not related to my script.  So closing this issue.

**Comment by zhangfangtaozft** [comment]
> Hello,
> I get this Linker Error while building for simulator or device.
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_FFBitstreamFilter", referenced from:
>       objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
>   "_OBJC_CLASS_$_FFOutputFile", referenced from:
>       objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
>   "_OBJC_CLASS_$_FFInputFile", referenced from:
>       objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
>   "_OBJC_CLASS_$_FFOutputStream", referenced from:
>       objc-class-ref in libFFmpegWrapper.a(FFmpegWrapper.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> I have added the following frameworks & libraries
> CoreMedia, VideoToolbox, libbz2, libbz, libiconv, libFFmpegWrapper.a
> 
> Any ideas where I'm going wrong?

Has your problem been solved? I have the same problem as yours.
