### ISSUE TITLE
x264 disable-asm for bit-code

### ISSUE THREAD

**Issue by weinixuehao** [kewlbear/FFmpeg-iOS-build-script#114]
1、in order for building x264 with bitcode supported, so have to configure -fembed-bitcode to CFLAGS in build_x264.sh, but due to x264 has asm optimization, therefore still not working and complain "add bitcode support".
2、it no longer complains this error if disable asm optimization. but has a new error!
I had spent much time to search in google, but no result for fix my answer.
below is details:
[config.log](https://github.com/kewlbear/FFmpeg-iOS-build-script/files/1534438/config.log)

**Comment by kewlbear** [comment]
That's strange. I've just built FFmpeg with x264 successfully using this script and kewlbear/x264 script.  I enabled both assembly and bitcode.  From your build log I can see you are using same scripts.  Did you modify any compile option?

**Comment by weinixuehao** [comment]
[build-ffmpeg的副本.txt](https://github.com/kewlbear/FFmpeg-iOS-build-script/files/1537567/build-ffmpeg.txt)
1、I did not modify any compile option but modified download source to last version of x264 and ffmpeg. I see some suggestion to remove -fembed-bitcode in build_ffmpeg.sh script to fix this issues. it works but complains "'xxx' is only available on iOS 8.0 or newer" so have to modify the DEPLOYMENT_TARGET option to 8.0. Finally compiled arm64 success!

**Comment by kewlbear** [comment]
Congrats!
