### ISSUE TITLE
IOS ffmpeg can not capture audio devices?

### ISSUE THREAD

**Issue by CAdolph** [kewlbear/FFmpeg-iOS-build-script#115]
I try to alter the configure message,now I can get the camera devices(Front and back), but can not the audio devices.
the configure I only add some settings:
--disable-all --disable-dxva2 --disable-vaapi --disable-vdpau --disable-vda \
--enable-avdevice --enable-avcodec --enable-avformat --enable-avutil --enable-swresample --enable-swscale --enable-postproc --enable-avfilter --enable-avresample \
 --enable-nonfree --enable-version3 --enable-pic --enable-small --enable-static \
 --enable-gpl \
 --enable-libx264 \
 --enable-libfdk-aac \
 --enable-libfaac \
 --enable-encoder=libx264 \
 --enable-encoder=libfaac \
 --enable-encoder=libfdk_aac \
 --enable-encoder=rawvideo \
 --enable-indev=avfoundation \

**Comment by kewlbear** [comment]
Please show relevant source code snippet you are using to get audio device.
