### ISSUE TITLE
Max bitrate property issue

### ISSUE THREAD

**Issue by ViswanathB84** [kewlbear/FFmpeg-iOS-build-script#117]
Thank you very much for developing and supporting this great FFMPEG libaray .

I am an iOS developer. I used FFMPEG library for video conversion i.e mpg format to mp4 format. I am getting below error in debug console. 

**Input #0, mpeg, from '/Users/Library/Developer/CoreSimulator/Devices/A71B16D3-86A9-4403-A6B1-9A8D23B842C0/data/Containers/Bundle/Application/FFA13844-61BD-4A81-9A2F-CACDB6BC6ADA/DLGDemo.app/iOSQuickstartMVVM.mpg':
  Duration: 00:05:15.69, start: 0.508278, bitrate: 982 kb/s
    Stream #0:0[0x1e0]: Video: mpeg1video, yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], 104857 kb/s, 30 fps, 30 tbr, 90k tbn, 30 tbc
    Stream #0:1[0x1c0]: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
[h264_videotoolbox @ 0x7ff34a018200] Error setting max bitrate property: -12902
Cannot open video encoder for stream #0
Error occurred: Generic error in an external library.**

Would you please help on this how to resolve this issue.
Thank you very much for your support.

**Comment by kewlbear** [comment]
You should show relevant source code of your app to get help from anyone.

**Comment by kewlbear** [comment]
You should log failing codec info and verify it is available. You may need to rebuild FFmpeg with more external libraries and/or `configure` options.

**Comment by ViswanathB84** [comment]
I rebuilded FFmpeg libraries and below libraries using for conversion but Still it is failing.
libavcodec.a
libavdevice.a
libavfilter.a
libavformat.a
libavresample.a
libavutil.a
libfdk-aac.a
libpostproc.a
libswresample.a
libswscale.a
libx264.a
Would you please suggest which external libraries or configure I need to use it for conversion.
