### ISSUE TITLE
FFmpeg Building script "building arm64" failed

### ISSUE THREAD

**Issue by mrpradipkumar46** [kewlbear/FFmpeg-iOS-build-script#120]
Hi,
According to your documentation, I am building script file and got the following error:

PRADEEP:FFmpeg-iOS-build-script-master Pradip$ ./build-ffmpeg.sh
building arm64...
xcrun -sdk iphoneos clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

And i have seen the latest FFmpeg build now came as 3.4.1, but this one 3.4. Please help me out why this error is there

**Comment by kewlbear** [comment]
It looks similar to #119 .

**Comment by mrpradipkumar46** [comment]
Thanks It happened bcoz of command tools update. It worked by adding the following commands
"sudo xcode-select --switch /Applications/Xcode.app" which is given by  mrbrantofgithub..thanks him too
