### ISSUE TITLE
invalid sh to build, how to solve the problem?

### ISSUE THREAD

**Issue by lakehubo** [kewlbear/FFmpeg-iOS-build-script#124]
./build-ffmpeg.sh
building arm64...
xcrun -sdk iphoneos clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by lakehubo** [comment]
this is build log
.....
check_ld cc
check_cc
BEGIN /var/folders/1t/ylg_rg4n5gg5ly8z_6xpwk180000gn/T/ffconf.8seEowVO/test.c
    1	int main(void){ return 0; }
END /var/folders/1t/ylg_rg4n5gg5ly8z_6xpwk180000gn/T/ffconf.8seEowVO/test.c
xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=9.0 -fembed-bitcode -c -o /var/folders/1t/ylg_rg4n5gg5ly8z_6xpwk180000gn/T/ffconf.8seEowVO/test.o /var/folders/1t/ylg_rg4n5gg5ly8z_6xpwk180000gn/T/ffconf.8seEowVO/test.c
xcrun: error: SDK "iphoneos" cannot be located
xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=9.0 -fembed-bitcode -o /var/folders/1t/ylg_rg4n5gg5ly8z_6xpwk180000gn/T/ffconf.8seEowVO/test /var/folders/1t/ylg_rg4n5gg5ly8z_6xpwk180000gn/T/ffconf.8seEowVO/test.o
xcrun: error: SDK "iphoneos" cannot be located
ld: warning: ignoring file /usr/lib/libSystem.dylib, missing required architecture arm64 in file /usr/lib/libSystem.dylib (2 slices)
ld: dynamic main executables must link with libSystem.dylib for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
C compiler test failed.

**Comment by kewlbear** [comment]
Have you installed command line tools?

**Comment by lakehubo** [comment]
you mean i have to installed the command line tools？OK，i will try it.

**Comment by lakehubo** [comment]
I checked it, i have installed command line tools in Mac.so what can I do to solve the problem?

**Comment by kewlbear** [comment]
See https://github.com/gomatcha/matcha/issues/6

**Comment by lakehubo** [comment]
thanks, it works.

**Comment by lakehubo** [comment]
thanks.it works.because I update Xcode to 9.2 version.than do that in terminal sudo xcode-select --switch /Applications/Xcode.app,the sh it works will.
