### ISSUE TITLE
build failed in xcode9.3

### ISSUE THREAD

**Issue by rentaogithub** [kewlbear/FFmpeg-iOS-build-script#125]
in xcode9.3 ，ffmpeg build failed , error info : src/libavutil/arm/asm.S:50:9: error: unknown directive
        .arch armv7-a

**Comment by kewlbear** [comment]
Confirmed build failing for armv7.  Looking for solutions.  Workarounds: remove armv7 if you don't need, get Xcode 9.2, or download binary if you don't need any customizations.

**Comment by zhuozhuo** [comment]
Same question.

**Comment by kewlbear** [comment]
Fixed in b98a5a1f77bd45b63e8bb5d790f5e5e1bae4eda6
