### ISSUE TITLE
iOS cannot use 'delogo'

### ISSUE THREAD

**Issue by daiyangyang945** [kewlbear/FFmpeg-iOS-build-script#127]
It log:'No such filter:delogo'
why?

**Comment by kewlbear** [comment]
Check `config.log` to see if  the filter is  enabled. If not, you should enable it by modifying `CONFIGURE_FLAGS`.

**Comment by daiyangyang945** [comment]
Thanks,I resolve it.
it is because 'delogo' belong to 'gpl',and it is disabled by default.

**Comment by kewlbear** [comment]
Glad I could help!
