### ISSUE TITLE
ERROR: libx264 not found

### ISSUE THREAD

**Issue by PlutoMa** [kewlbear/FFmpeg-iOS-build-script#131]
This is my sh file

[build-ffmpeg.txt](https://github.com/kewlbear/FFmpeg-iOS-build-script/files/2105575/build-ffmpeg.txt)
this is my folder
![image](https://user-images.githubusercontent.com/18652191/41461857-854ad49c-70c3-11e8-9d1a-44e78dd4086a.png)
FFmpeg: 3.3.6

**Comment by kewlbear** [comment]
You need to download and build x264 before running this script.

**Comment by PlutoMa** [comment]
I have downloaded and builded it. fat-x264 is the result.

**Comment by PlutoMa** [comment]
I have already solved this problem. The reason is that the nasm version is too low.
