### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by 930410127** [kewlbear/FFmpeg-iOS-build-script#132]
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols for architecture arm64:
  "_x264_encoder_close", referenced from:
      _X264_close in libavcodec.a(libx264.o)
  "_x264_encoder_reconfig", referenced from:
      _X264_frame in libavcodec.a(libx264.o)
  "_x264_encoder_delayed_frames", referenced from:
      _X264_frame in libavcodec.a(libx264.o)
  "_x264_param_apply_fastfirstpass", referenced from:
      _X264_init in libavcodec.a(libx264.o)
  "_aacDecoder_Close", referenced from:
      _fdk_aac_decode_close in libavcodec.a(libfdk-aacdec.o)
  "_x264_levels", referenced from:
      _X264_init in libavcodec.a(libx264.o)
  "_x264_param_parse", referenced from:
      _X264_init in libavcodec.a(libx264.o)
  "_x264_picture_init", referenced from:
      _X264_frame in libavcodec.a(libx264.o)
  "_aacDecoder_SetParam", referenced from:
      _fdk_aac_decode_init in libavcodec.a(libfdk-aacdec.o)
      _fdk_aac_decode_flush in libavcodec.a(libfdk-aacdec.o)
  "_x264_encoder_open_155", referenced from:
      _X264_init in libavcodec.a(libx264.o)
  "_aacEncClose", referenced from:
      _aac_encode_close in libavcodec.a(libfdk-aacenc.o)
  "_aacDecoder_AncDataInit", referenced from:
      _fdk_aac_decode_init in libavcodec.a(libfdk-aacdec.o)
  "_aacEncoder_SetParam", referenced from:
      _aac_encode_init in libavcodec.a(libfdk-aacenc.o)
  "_x264_encoder_encode", referenced from:
      _X264_frame in libavcodec.a(libx264.o)
  "_aacEncEncode", referenced from:
      _aac_encode_init in libavcodec.a(libfdk-aacenc.o)
      _aac_encode_frame in libavcodec.a(libfdk-aacenc.o)

What is the problem? Please enlighten me.Thanks！

**Comment by fukemy** [comment]
this owner did not answer the question. So bad
