### ISSUE TITLE
X86_64 error

### ISSUE THREAD

**Issue by zhangfangtaozft** [kewlbear/FFmpeg-iOS-build-script#136]
Undefined symbols for architecture x86_64:
  "_avcodec_configuration", referenced from:
      -[ViewController viewDidLoad] in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zhangfangtaozft** [comment]
Like this:
![image](https://user-images.githubusercontent.com/11926205/48462999-77ffa500-e815-11e8-9e5e-4be621bfbf6d.png)
and
![image](https://user-images.githubusercontent.com/11926205/48463025-8948b180-e815-11e8-98ae-c7b78710166f.png)

and
![41542175610_ pic](https://user-images.githubusercontent.com/11926205/48463303-9023f400-e816-11e8-9c38-2c993df0c307.jpg)

**Comment by kewlbear** [comment]
Seems good to me. What do you see when you run `file FFmpeg-iOS/lib/libavcodec.a`? I see the following:

```
$ file FFmpeg-iOS/lib/libavcodec.a 
FFmpeg-iOS/lib/libavcodec.a: Mach-O universal binary with 4 architectures: [i386:current ar archive random library] [arm64]
FFmpeg-iOS/lib/libavcodec.a (for architecture i386):	current ar archive random library
FFmpeg-iOS/lib/libavcodec.a (for architecture armv7):	current ar archive random library
FFmpeg-iOS/lib/libavcodec.a (for architecture x86_64):	current ar archive random library
FFmpeg-iOS/lib/libavcodec.a (for architecture arm64):	current ar archive random library
```

**Comment by zhangfangtaozft** [comment]
It has been solved, Thank you.
