### ISSUE TITLE
How to build with libfreetype?

### ISSUE THREAD

**Issue by qoakzmxncb** [kewlbear/FFmpeg-iOS-build-script#137]
I want to use the drawtext function on iOS, so I added --enable-libfreetype to CONFIGURE_FLAGS. But there is a freetype2 not found error, how can I solve it?

**Comment by qoakzmxncb** [comment]
and I have installed freetype by brew, but the error still appears
my Xcode version is 10.1 . and OS X is 10.14

**Comment by qoakzmxncb** [comment]
I have download the FFMpeg source code with version 3.0.12,
 and use ./configure --enable-libfreetype
make
make install
everything is done.
So what's the problem with build-ffmpeg.sh ? @kewlbear

**Comment by kewlbear** [comment]
You need freetype compiles for iOS. What you installed using brew is for macOS.

**Comment by qoakzmxncb** [comment]
> You need freetype compiles for iOS. What you installed using brew is for macOS.

Yes, I know that.But when I use build-ffmpeg.sh with '--enable-libfreetype', always prompt an error 'freetype2 not found'
I do not know how to fix it...

**Comment by kewlbear** [comment]
You should download freetype source and build for iOS. Then edit this script to let configure know where to find freetype headers and library. Then run it.
