### ISSUE TITLE
ERROR: dav1d >= 0.4.0 not found using pkg-config

### ISSUE THREAD

**Issue by Aduir** [kewlbear/FFmpeg-iOS-build-script#154]
in file ./build-ffmpeg.sh, I add --enable-libdav1d. and then run ./build-ffmpeg.sh, it shows "ERROR: dav1d >= 0.4.0 not found using pkg-config"

> CONFIGURE_FLAGS="--enable-cross-compile --disable-debug --disable-programs \
>                  --disable-doc --enable-pic --enable-libdav1d"

**Comment by kewlbear** [comment]
You should build libdav1d for iOS and provide the path to it like I do for x264.

**Comment by Aduir** [comment]
> You should build libdav1d for iOS and provide the path to it like I do for x264.

Thank you!
how I build libdav1d for iOS
can you say any more detail?
