### ISSUE TITLE
Not support OBS Studio use NVENC encodec

### ISSUE THREAD

**Issue by 8MiYile** [kewlbear/FFmpeg-iOS-build-script#157]
please add options --shared or -s in script
thx

**Comment by kewlbear** [comment]
iOS devices doesn't have Nvidia cards.

**Comment by 8MiYile** [comment]
> iOS devices doesn't have Nvidia cards.

Linux Deepin 20

**Comment by kewlbear** [comment]
This project is not for Linux.
