### ISSUE TITLE
 C compiler cannot create executables

### ISSUE THREAD

**Issue by Vetagiri-Hrushikesh** [kewlbear/FFmpeg-iOS-build-script#159]
Iam running with this problem in i386 when I build the given script. Can anyone help me.

building i386...
```
configure:3656: $? = 0
configure:3645: /usr/bin/gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3656: $? = 1
configure:3645: /usr/bin/gcc -qversion >&5
clang: error: unknown argument '-qversion'; did you mean '--version'?
clang: error: no input files
configure:3656: $? = 1
configure:3676: checking whether the C compiler works
configure:3698: /usr/bin/gcc -arch i386 -mios-simulator-version-min=5.0 -fembed-bitcode  -arch i386 -mios-simulator-version-min=5.0 -fembed-bitcode conftest.c  >&5
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd (3 slices)
Undefined symbols for architecture i386:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3702: $? = 1
configure:3740: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "lame"
| #define PACKAGE_TARNAME "lame"
| #define PACKAGE_VERSION "3.100"
| #define PACKAGE_STRING "lame 3.100"
| #define PACKAGE_BUGREPORT "lame-dev@lists.sf.net"
| #define PACKAGE_URL ""
| #define PACKAGE "lame"
| #define VERSION "3.100"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3745: error: in `/Users/mac/Desktop/Organize/Personal/MaighaCom/TestingSources/maiSources/ffmpeg_build/platforms/ffmpeg_build_ios/scratch-lame/i386':
configure:3747: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by kewlbear** [comment]
Do you really need i386?  Are you building it for iOS?

**Comment by Vetagiri-Hrushikesh** [comment]
> Do you really need i386? Are you building it for iOS?

Yes Iam building it for iOS.

**Comment by kewlbear** [comment]
> 		if [ "$X264" ]
> 		then
> 			CFLAGS="$CFLAGS -I$X264/include"
> 			LDFLAGS="$LDFLAGS -L$X264/lib"
> 		fi
> 		if [ "$FDK_AAC" ]
> 		then
> 			CFLAGS="$CFLAGS -I$FDK_AAC/include"
> 			LDFLAGS="$LDFLAGS -L$FDK_AAC/lib"
> 		fi

You have to add something like above for lame.

**Comment by Vetagiri-Hrushikesh** [comment]
I got it. But While building the lame script Iam unable to build for i386 architecture. Iam always ending with [this](https://github.com/kewlbear/FFmpeg-iOS-build-script/issues/159#issue-882606280). I guess ffmpeg-ios will build if this issue(while building i386 in lame) is resolved. Can you help me to build the lame properly.

Thank you

**Comment by kewlbear** [comment]
Did you install command line tools?  Can you share config.log?

**Comment by Vetagiri-Hrushikesh** [comment]
> Did you install command line tools? Can you share config.log?

Yeah sure, This is my config.log while building i386 ( for lame script ), Others(arm64 armv7s x86_64 armv7) are running fine.

[config.log](https://github.com/kewlbear/FFmpeg-iOS-build-script/files/6463870/config.log)

**Comment by kewlbear** [comment]
I can reproduce it.  Do you really need i386?  If not, I think you'd better remove i386 from both lame and ffmpeg build scripts.

**Comment by Vetagiri-Hrushikesh** [comment]
> I can reproduce it. Do you really need i386? If not, I think you'd better remove i386 from both lame and ffmpeg build scripts.

Yeah for now I did removed 1386 and compiled both the libraries and it is working fine. 
Thank you.
