### ISSUE TITLE
ffmpeg 4.4.1 not work

### ISSUE THREAD

**Issue by TimeIsRunning** [kewlbear/FFmpeg-iOS-build-script#161]
when I used the script compile ffmpeg-4.4.1 and report an error,this version seems to conflictted with system's AudioToolBox,
 detail:
src/libavdevice/audiotoolbox.m:78:5: error: unknown type name 'AudioDeviceID'; did you mean 'AudioFileID'?
    AudioDeviceID *devices;
    
Think you!!!

**Comment by William-Friday** [comment]
It's also a problem for me

**Comment by TimeIsRunning** [comment]
I used '--disable-audiotoolbox' that it's working, maybe you can try it if your's project don't used this lib

**Comment by William-Friday** [comment]
it's working, thank you
