### ISSUE TITLE
Build Error for `xrealloc: cannot allocate 18446744071595622528 bytes`

### ISSUE THREAD

**Issue by RenderCoder** [kewlbear/FFmpeg-iOS-build-script#165]
Hi,

I want to build a version for iOS simulator for M1 MacBook, clone and execute this command:

```shell
./build-ffmpeg.sh armv7 x86_64
```

and then, it shows some error:

```shell
checking=inprogress: command not found
/.../FFmpeg-iOS-build-script/ffmpeg-4.3.1/configure: xrealloc: cannot allocate 18446744071595622528 bytes
```

![Bevis_2022-04-20_at_11 56 29](https://user-images.githubusercontent.com/2999386/164147340-e3537e75-34ac-41b0-b297-e4ae31818b6b.png)

please help me to solve this problem, thanks!

**Comment by kewlbear** [comment]
Consider using my FFmpeg-iOS Swift package.
