### ISSUE TITLE
how to support lanme

### ISSUE THREAD

**Issue by hunter858** [kewlbear/FFmpeg-iOS-build-script#166]

**Comment by kewlbear** [comment]
What's lanme?

**Comment by hunter858** [comment]
mp3lame

**Comment by kewlbear** [comment]
How about this?

https://github.com/kewlbear/lame-ios-build

**Comment by hunter858** [comment]
Ok，this ‘lame-ios-build’ can used, I want know why you script not contain build mp3lame config ? 
ffmpeg default not support mp3 encoder ,I suggest you add build mp3lame config ;

**Comment by kewlbear** [comment]
After building lame, you can edit this script to enable it in ffmpeg. Not everyone need the lame mp3 encoder.

**Comment by hunter858** [comment]
thank you
