### ISSUE TITLE
ffmpeg v6.0 build-script Failed！

### ISSUE THREAD

**Issue by JadeXH** [kewlbear/FFmpeg-iOS-build-script#170]
system：MacOS12.6.3
 
```
./build-ffmpeg.sh
building arm64...
./build-ffmpeg.sh: line 135: /usr/local/Cellar/ffmpeg/6.0/configure: No such file or directory
```
？？？“How does this configure need to be configured”

FF_VERSION="6.0"
SOURCE="/usr/local/Cellar/ffmpeg/$FF_VERSION"
--- 135 row -----
```
		TMPDIR=${TMPDIR/%\/} $SOURCE/configure \
		    --target-os=darwin \
		    --arch=$ARCH \
		    --cc="$CC" \
		    --as="$AS" \
		    $CONFIGURE_FLAGS \
		    --extra-cflags="$CFLAGS" \
		    --extra-ldflags="$LDFLAGS" \
		    --prefix="$THIN/$ARCH" \
		|| exit 1
```

**Comment by kewlbear** [comment]
Looks like you are trying to build using homebrew installation of FFmpeg.  You should download FFmpeg source directly from FFmpeg.org.

**Comment by JadeXH** [comment]
Fixed, brew install ffmpeg download is not source code, download ok from official website
