### ISSUE TITLE
GNU assembler not found, install/update gas-preprocessor

### ISSUE THREAD

**Issue by oniru** [kewlbear/FFmpeg-iOS-build-script#20]
Although, I have copied gas-preprocessor.pl into the directories /usr/local/bin and /usr/bin and modified the file read-write props by using chmod +x gas-preprocessor.pl

my environment is ios8 & yosemite 10.10 version.

**Comment by bighk** [comment]
hi  kewlbear:
i downloaded your script and  run it . 
Here is the result:

WARNING: pkg-config not found, library dection may fail.
/Users/apple/ffmpeg-2.5.3/Makefile:185:/Users/apple/ffmpeg-2.5.3/Makefile: NO  such file or directory
make :***NO rule to make target "/Users/apple/ffmpeg-2.5.3/Makefile".stop

how to fix this problem?

osx 10.9.5 xcode 6.1.1

**Comment by nomadli** [comment]
hi
   the script fork frome https://github.com/kewlbear/FFmpeg-iOS-build-script‍




------------------ 原始邮件 ------------------
发件人: "bighk";<notifications@github.com>;
发送时间: 2015年1月29日(星期四) 上午10:34
收件人: "kewlbear/FFmpeg-iOS-build-script"<FFmpeg-iOS-build-script@noreply.github.com>; 
抄送: "Nomad"<dzym79@qq.com>; 
主题: Re: [FFmpeg-iOS-build-script] GNU assembler not found, install/updategas-preprocessor (#20)




hi  kewlbear:
 i downloaded your script and  run it . 
 Here is the result:
 
WARNING: pkg-config not found, library dection may fail.
 /Users/apple/ffmpeg-2.5.3/Makefile:185:/Users/apple/ffmpeg-2.5.3/Makefile: NO  such file or directory
 make :***NO rule to make target "/Users/apple/ffmpeg-2.5.3/Makefile".stop
 
how to fix this problem?
 
osx 10.9.5 xcode 6.1.1

**Comment by nomadli** [comment]
gas-preprocessor.pl‍ the perl script don't manual installation, it will auto install‍



------------------ 原始邮件 ------------------
发件人: "bighk";<notifications@github.com>;
发送时间: 2015年1月29日(星期四) 上午10:34
收件人: "kewlbear/FFmpeg-iOS-build-script"<FFmpeg-iOS-build-script@noreply.github.com>; 
抄送: "Nomad"<dzym79@qq.com>; 
主题: Re: [FFmpeg-iOS-build-script] GNU assembler not found, install/updategas-preprocessor (#20)




hi  kewlbear:
 i downloaded your script and  run it . 
 Here is the result:
 
WARNING: pkg-config not found, library dection may fail.
 /Users/apple/ffmpeg-2.5.3/Makefile:185:/Users/apple/ffmpeg-2.5.3/Makefile: NO  such file or directory
 make :***NO rule to make target "/Users/apple/ffmpeg-2.5.3/Makefile".stop
 
how to fix this problem?
 
osx 10.9.5 xcode 6.1.1

**Comment by kewlbear** [comment]
You should've opened a new issue. Anyways please copy and paste complete output. I have no idea from your comment.
