### ISSUE TITLE
Header file not found

### ISSUE THREAD

**Issue by myqiqiang** [kewlbear/FFmpeg-iOS-build-script#21]
After i build it,and finally it shows "Done",so i think it built successfully.
Then i import it to a new xcode project and build.
it reports libavutil/samplefmt.h not found,not only this one,all the  "liba***/***.h"format #include have same error.

**Comment by cclili** [comment]
me too;i copy all the include to header search path ,also this problem

**Comment by kewlbear** [comment]
Don't copy the files. Just add absolute/or/relative/path/to/FFmpeg-iOS/include directory to header search path.

**Comment by cclili** [comment]
非常感谢！！！！！
