### ISSUE TITLE
Usage - ios8 and more

### ISSUE THREAD

**Issue by Ankish** [kewlbear/FFmpeg-iOS-build-script#23]
You can download a binary for FFmpeg 2.5.3 release at https://downloads.sourceforge.net/project/ffmpeg-ios/ffmpeg-ios-master.tar.bz2

Can i download this drag and drop the file and use ? I am totally new to this.
Or is it mandatory for me to run the scripts and generate the files.?

And things look different for ios8 and xcode 6.1 , a possbile script update?

**Comment by kewlbear** [comment]
You can download and use the binary. But if you need some codecs not included in the binary, you should edit the script and build it yourself. The binary and the script both work with iOS 8 and Xcode 6.1.

**Comment by Ankish** [comment]
thanks
