### ISSUE TITLE
ffmpeg build fail 

### ISSUE THREAD

**Issue by bighk** [kewlbear/FFmpeg-iOS-build-script#25]
I put the script file  and ffmpeg source in the same folder, after run it , there is a warning .
osx version is 10.9.5 xcode version is 6.1.1
here is the output:

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
install prefix               /Users/apple/thin/arm64
source path               /Users/apple/ffmpeg-2.5.3
C compiler                 xcrun -sdk iphoneos clang
C library                 
host C compiler           gcc
host C library            
ARCH                          aarch64 (generic)
big-endian                   no
runtime cpu detection    yes
NEON enabled               yes
VFP enabled                  yes
debug symbols               no
strip symbols                   yes
optimize for size              no
optimizations                  yes
static                              yes
shared                           no
postprocessing support    no
new filter support            yes
network support              yes
threading support           pthreads
safe bitstream reader     yes
SDL support                   no
opencl enabled               no
texi2html enabled            no
perl enabled                    yes
pod2man enabled           yes
makeinfo enabled           yes
makeinfo supports HTML    no

External libraries:
bzlib			iconv			zlib

Enabled decoders:
aac			bfi			       gsm
aac_latm		bink			       gsm_ms
aasc			binkaudio_dct		h261
ac3			binkaudio_rdft		h263
ac3_fixed		bintext			h263i
adpcm_4xm	bmp			        h263p
adpcm_adx	bmv_audio		h264
adpcm_afc	bmv_video		hevc
adpcm_ct		brender_pix		hnm4_video
adpcm_dtk	c93			        huffyuv
adpcm_ea	cavs			        iac
adpcm_ea_maxis_xa	cdgraphics		idcin
adpcm_ea_r1		cdxl			idf
adpcm_ea_r2		cinepak			iff_byterun1
adpcm_ea_r3		cljr			iff_ilbm
adpcm_ea_xas		cllc			imc
adpcm_g722		comfortnoise		indeo2
adpcm_g726		cook			indeo3
adpcm_g726le		cpia			indeo4
adpcm_ima_amv	cscd			indeo5
adpcm_ima_apc	cyuv			interplay_dpcm
adpcm_ima_dk3	dca			interplay_video
adpcm_ima_dk4	dfa			jacosub
adpcm_ima_ea_eacs	dirac			jpeg2000
adpcm_ima_ea_sead	dnxhd			jpegls
adpcm_ima_iss		dpx			jv
adpcm_ima_oki		dsd_lsbf		kgv1
adpcm_ima_qt		        dsd_lsbf_planar		kmvc
adpcm_ima_rad		dsd_msbf		lagarith
adpcm_ima_smjpeg	dsd_msbf_planar		loco
adpcm_ima_wav		dsicinaudio		mace3
adpcm_ima_ws		dsicinvideo		mace6
adpcm_ms		       dvbsub			mdec
adpcm_sbpro_2		dvdsub			metasound
adpcm_sbpro_3		dvvideo			microdvd
adpcm_sbpro_4		dxa			mimic
adpcm_swf		       dxtory			mjpeg
adpcm_thp		       eac3			mjpegb
adpcm_vima		       eacmv			mlp
adpcm_xa		       eamad			mmvideo
adpcm_yamaha		eatgq			motionpixels
aic			eatgv			movtext
alac			eatqi			mp1
alias_pix		eightbps		mp1float
als			eightsvx_exp		mp2
amrnb			eightsvx_fib		mp2float
amrwb			escape124		mp3
amv			escape130		mp3adu
anm			evrc			mp3adufloat
ansi			exr			mp3float
ape			ffv1			mp3on4
apng			ffvhuff			mp3on4float
ass			ffwavesynth		mpc7
asv1			fic			mpc8
asv2			flac			mpeg1video
atrac1			flashsv			mpeg2video
atrac3			flashsv2		mpeg4
atrac3p			flic			mpegvideo
aura			flv			mpl2
aura2			fourxm			msa1
avrn			fraps			msmpeg4v1
avrp			frwu			msmpeg4v2
avs			g2m			msmpeg4v3
avui			g723_1			msrle
ayuv			g729			mss1
bethsoftvid		gif			mss2
msvideo1		qpeg			txd
mszh			qtrle			ulti
mts2			r10k			utvideo
mvc1			r210			v210
mvc2			ra_144			v210x
mxpeg			ra_288			v308
nellymoser		ralf			v408
nuv			rawvideo		v410
on2avc			realtext		vb
opus			rl2			vble
paf_audio		roq			vc1
paf_video		roq_dpcm		vc1image
pam			rpza			vcr1
pbm			rv10			vima
pcm_alaw		rv20			vmdaudio
pcm_bluray		rv30			vmdvideo
pcm_dvd			rv40			vmnc
pcm_f32be		s302m			vorbis
pcm_f32le		sami			vp3
pcm_f64be		sanm			vp5
pcm_f64le		sgi			vp6
pcm_lxf			sgirle			vp6a
pcm_mulaw		shorten			vp6f
pcm_s16be		sipr			vp7
pcm_s16be_planar	smackaud		vp8
pcm_s16le		smacker			vp9
pcm_s16le_planar	smc			vplayer
pcm_s24be		smvjpeg			vqa
pcm_s24daud		snow			wavpack
pcm_s24le		sol_dpcm		webp
pcm_s24le_planar	sonic			webvtt
pcm_s32be		sp5x			wmalossless
pcm_s32le		srt			wmapro
pcm_s32le_planar	ssa			wmav1
pcm_s8			stl			wmav2
pcm_s8_planar		subrip			wmavoice
pcm_u16be		subviewer		wmv1
pcm_u16le		subviewer1		wmv2
pcm_u24be		sunrast			wmv3
pcm_u24le		svq1			wmv3image
pcm_u32be		svq3			wnv1
pcm_u32le		tak			ws_snd1
pcm_u8			targa			xan_dpcm
pcm_zork		targa_y216		xan_wc3
pcx			text			xan_wc4
pgm			theora			xbin
pgmyuv			thp			xbm
pgssub			tiertexseqvideo		xface
pictor			tiff			xl
pjs			tmv			xsub
png			truehd			xwd
ppm			truemotion1		y41p
prores			truemotion2		yop
prores_lgpl		truespeech		yuv4
ptx			tscc			zero12v
qcelp			tscc2			zerocodec
qdm2			tta			zlib
qdraw			twinvq			zmbv

Enabled encoders:
a64multi		jpegls			prores
a64multi5		ljpeg			prores_aw
aac			mjpeg			prores_ks
ac3			movtext			qtrle
ac3_fixed		mp2			r10k
adpcm_adx		mp2fixed		r210
adpcm_g722		mpeg1video		ra_144
adpcm_g726		mpeg2video		rawvideo
adpcm_ima_qt		mpeg4			roq
adpcm_ima_wav		msmpeg4v2		roq_dpcm
adpcm_ms		msmpeg4v3		rv10
adpcm_swf		msvideo1		rv20
adpcm_yamaha		nellymoser		s302m
alac			pam			sgi
alias_pix		pbm			snow
amv			pcm_alaw		sonic
ass			pcm_f32be		sonic_ls
asv1			pcm_f32le		srt
asv2			pcm_f64be		ssa
avrp			pcm_f64le		subrip
avui			pcm_mulaw		sunrast
ayuv			pcm_s16be		svq1
bmp			pcm_s16be_planar	targa
cinepak			pcm_s16le		tiff
cljr			pcm_s16le_planar	tta
comfortnoise		pcm_s24be		utvideo
dca			pcm_s24daud		v210
dnxhd			pcm_s24le		v308
dpx			pcm_s24le_planar	v408
dvbsub			pcm_s32be		v410
dvdsub			pcm_s32le		vorbis
dvvideo			pcm_s32le_planar	wavpack
eac3			pcm_s8			webvtt
ffv1			pcm_s8_planar		wmav1
ffvhuff			pcm_u16be		wmav2
flac			pcm_u16le		wmv1
flashsv			pcm_u24be		wmv2
flashsv2		pcm_u24le		xbm
flv			pcm_u32be		xface
g723_1			pcm_u32le		xsub
gif			pcm_u8			xwd
h261			pcx			y41p
h263			pgm			yuv4
h263p			pgmyuv			zlib
huffyuv			png			zmbv
jpeg2000		ppm
Enabled hwaccels:

Enabled parsers:
aac			dvd_nav			mpegvideo
aac_latm		dvdsub			opus
ac3			flac			png
adx			gsm			pnm
bmp			h261			rv30
cavsvideo		h263			rv40
cook			h264			tak
dca			hevc			vc1
dirac			mjpeg			vorbis
dnxhd			mlp			vp3
dpx			mpeg4video		vp8
dvbsub			mpegaudio		vp9
Enabled demuxers:
aac			h261			mxg
ac3			h263			nc
act			h264			nistsphere
adf			hevc			nsv
adp			hls			nut
adx			hnm			nuv
aea			ico			ogg
afc			idcin			oma
aiff			idf			paf
amr			iff			pcm_alaw
anm			ilbc			pcm_f32be
apc			image2			pcm_f32le
ape			image2_alias_pix	pcm_f64be
apng			image2_brender_pix	pcm_f64le
aqtitle			image2pipe		pcm_mulaw
asf			image_bmp_pipe		pcm_s16be
ass			image_dpx_pipe		pcm_s16le
ast			image_exr_pipe		pcm_s24be
au			image_j2k_pipe		pcm_s24le
avi			image_jpeg_pipe		pcm_s32be
avr			image_jpegls_pipe	pcm_s32le
avs			image_pictor_pipe	pcm_s8
bethsoftvid		image_png_pipe		pcm_u16be
bfi			image_sgi_pipe		pcm_u16le
bink			image_sunrast_pipe	pcm_u24be
bintext			image_tiff_pipe		pcm_u24le
bit			image_webp_pipe		pcm_u32be
bmv			ingenient		pcm_u32le
boa			ipmovie			pcm_u8
brstm			ircam			pjs
c93			iss			pmp
caf			iv8			pva
cavsvideo		ivf			pvf
cdg			jacosub			qcp
cdxl			jv			r3d
cine			latm			rawvideo
concat			live_flv		realtext
data			lmlm4			redspark
daud			loas			rl2
dfa			lrc			rm
dirac			lvf			roq
dnxhd			lxf			rpl
dsf			m4v			rsd
dsicin			matroska		rso
dts			mgsts			rtp
dtshd			microdvd		rtsp
dv			mjpeg			sami
dxa			mlp			sap
ea			mlv			sbg
ea_cdata		mm			sdp
eac3			mmf			sdr2
epaf			mov			segafilm
ffm			mp3			shorten
ffmetadata		mpc			siff
filmstrip		mpc8			sln
flac			mpegps			smacker
flic			mpegts			smjpeg
flv			mpegtsraw		smush
fourxm			mpegvideo		sol
frm			mpl2			sox
g722			mpsub			spdif
g723_1			msnwc_tcp		srt
g729			mtv			stl
gif			mv			str
gsm			mvi			subviewer
gxf			mxf			subviewer1
sup			vc1t			wsaud
swf			vivo			wsvqa
tak			vmd			wtv
tedcaptions		vobsub			wv
thp			voc			xa
tiertexseq		vplayer			xbin
tmv			vqf			xmv
truehd			w64			xwma
tta			wav			yop
tty			wc3			yuv4mpegpipe
txd			webm_dash_manifest
vc1			webvtt

Enabled muxers:
a64			image2pipe		pcm_s24be
ac3			ipod			pcm_s24le
adts			ircam			pcm_s32be
adx			ismv			pcm_s32le
aiff			ivf			pcm_s8
amr			jacosub			pcm_u16be
asf			latm			pcm_u16le
asf_stream		lrc			pcm_u24be
ass			m4v			pcm_u24le
ast			matroska		pcm_u32be
au			matroska_audio		pcm_u32le
avi			md5			pcm_u8
avm2			microdvd		psp
bit			mjpeg			rawvideo
caf			mkvtimestamp_v2		rm
cavsvideo		mlp			roq
crc			mmf			rso
dash			mov			rtp
data			mp2			rtsp
daud			mp3			sap
dirac			mp4			segment
dnxhd			mpeg1system		smjpeg
dts			mpeg1vcd		smoothstreaming
dv			mpeg1video		sox
eac3			mpeg2dvd		spdif
f4v			mpeg2svcd		spx
ffm			mpeg2video		srt
ffmetadata		mpeg2vob		stream_segment
filmstrip		mpegts			swf
flac			mpjpeg			tee
flv			mxf			tg2
framecrc		mxf_d10			tgp
framemd5		null			truehd
g722			nut			uncodedframecrc
g723_1			oga			vc1
gif			ogg			vc1t
gxf			oma			voc
h261		opus			w64
h263		pcm_alaw		wav
h264		pcm_f32be	webm
hds			pcm_f32le	webm_dash_manifest
hevc			pcm_f64be	webp
hls			pcm_f64le	webvtt
ico			pcm_mulaw	wtv
ilbc			pcm_s16be	wv
image2		pcm_s16le	yuv4mpegpipe

Enabled protocols:
cache	       http			rtp
concat		httpproxy		srtp
crypto		icecast		subfile
data			md5			tcp
ffrtmphttp		mmsh		udp
file			mmst		udplite
ftp			pipe			unix
gopher		rtmp
hls			rtmpt

Enabled filters:
adelay			crop			overlay
aecho			curves			pad
aeval			dctdnoiz		pan
aevalsrc		decimate		perms
afade			dejudder		pixdesctest
aformat			deshake			psnr
ainterleave		drawbox			removelogo
allpass			drawgrid		replaygain
alphaextract		earwax			rgbtestsrc
alphamerge		edgedetect		rotate
amerge			elbg			scale
amix			equalizer		select
amovie			extractplanes		sendcmd
anull			fade			separatefields
anullsink		field			setdar
anullsrc		fieldmatch		setfield
apad			fieldorder		setpts
aperms			flanger			setsar
aphaser			format			settb
aresample		fps			showcqt
aselect			framepack		showinfo
asendcmd		framestep		showspectrum
asetnsamples		gradfun			showwaves
asetpts			haldclut		shuffleplanes
asetrate		haldclutsrc		signalstats
asettb			hflip			silencedetect
ashowinfo		highpass		silenceremove
asplit			histogram		sine
astats			hqx			smptebars
astreamsync		hue			smptehdbars
atempo			idet			split
atrim			il			swapuv
avectorscope		interleave		telecine
bandpass		join			testsrc
bandreject		lenscorrection		thumbnail
bass			life			tile
bbox			lowpass			transpose
biquad			lut			treble
blackdetect		lut3d			trim
blend			lutrgb			unsharp
cellauto		lutyuv			vflip
channelmap		mandelbrot		vignette
channelsplit		mergeplanes		volume
codecview		movie			volumedetect
color			negate			w3fdif
colorbalance		noformat		xbr
colorchannelmixer	noise			yadif
compand			null			zoompan
concat			nullsink
copy			nullsrc

Enabled bsfs:
aac_adtstoasc		imx_dump_header		mp3_header_decompress
chomp			mjpeg2jpeg		noise
dump_extradata		mjpega_dump_header	remove_extradata
h264_mp4toannexb	mov2textsub		text2movsub

Enabled indevs:
avfoundation		lavfi

Enabled outdevs:

License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...
config.h is unchanged
libavutil/avconfig.h is unchanged

WARNING: pkg-config not found, library detection may fail.
/Users/apple/ffmpeg-2.5.3/Makefile:185: /Users/apple/ffmpeg-2.5.3/tests/Makefile: No such file or directory
make: *** No rule to make target `/Users/apple/ffmpeg-2.5.3/tests/Makefile'.  Stop.

**Comment by kewlbear** [comment]
There should be a Makefile in tests directory of FFmpeg source. Above error occurs because the file is missing. Download or unpack the source again. Or delete source directory and let the script download it.

**Comment by bighk** [comment]
follow your advise,it works perfect.your work is amazing.Thanks very much

**Comment by kewlbear** [comment]
Glad I could help.
