### ISSUE TITLE
Missing config.h in binary distribution

### ISSUE THREAD

**Issue by jlcastillo** [kewlbear/FFmpeg-iOS-build-script#27]
Thanks for the binary, but you forgot to add the config.h header. It should be in the root of the "include" folder.

**Comment by kewlbear** [comment]
Why do you need it? "make install" doesn't install the file. Also zeranoe dev package doesn't include it.

**Comment by jlcastillo** [comment]
You need it in order to know what options where used in configure script. Some programs depend on this. Look at ffmpeg.h.

**Comment by kewlbear** [comment]
You can see and change configure options in the script. And the archive also contains config.logs. I think apps using FFmpeg should not depend on ffmpeg.h because it is not public interface.
