### ISSUE TITLE
compile with x264

### ISSUE THREAD

**Issue by yaronj** [kewlbear/FFmpeg-iOS-build-script#28]
When uncomment the #X264=`pwd`/fat-x264 I get: ERROR: libx264 not found
I did put the libx264.a under the fat-x264

any idea?

**Comment by kewlbear** [comment]
You need "lib" and "include" directories under fat-x264. "lib" contains .a file. "include" contains .h files.

**Comment by yaronj** [comment]
thanks, found it
This is FFmpeg issue so I'm trying to find how to add support for this.
