### ISSUE TITLE
No accelerated colorspace conversion found from yuv420p to rgb24

### ISSUE THREAD

**Issue by yaronj** [kewlbear/FFmpeg-iOS-build-script#29]
I was looking around to find the reason for the warning while running with the compiled FFmpeg:
"No accelerated colorspace conversion found from yuv420p to rgb24"
and found it's related to the reason of not usging the GPU.

did the following with no difference:
1.  compiled the FFmpeg with x264 
2.  added to the configure flags: --enable-neon

this warning become when calling:
sws_getContext with PIX_FMT_RGB24 where the source is YUV420P

**Comment by kewlbear** [comment]
Actually the code is at line 669 of https://github.com/FFmpeg/FFmpeg/blob/master/libswscale/yuv2rgb.c. You can see there they only have accelerated conversions for PPC and X86.
