### ISSUE TITLE
How to convert .h264 file to .mp4 in iOS programmatically ? 

### ISSUE THREAD

**Issue by allamrajukrish** [kewlbear/FFmpeg-iOS-build-script#30]
Hi kewlbear,
Thank you very much for entire explanation to set up FFmpeg for iOS. I followed each step and successfully installed everything. I have a problem that i have to convert .h264 file to .mp4. Here is my question I have a .h264 file in my xcode project bundle, i have to convert the file in to .mp4, how to do this programmatically using this FFmpeg in Xcode?
Please give any suggestions or any snippet of code.

Thank you.

**Comment by kewlbear** [comment]
You should see https://ffmpeg.org/doxygen/trunk/transcoding_8c.html And adapt it to fit your requirements.
