### ISSUE TITLE
building armv7. fail

### ISSUE THREAD

**Issue by DongjieLi** [kewlbear/FFmpeg-iOS-build-script#32]
building arm64...   It succeed.
building armv7...
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
GNU assembler not found, install/update gas-preprocessor

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

**Comment by kewlbear** [comment]
Find and delete all gas-preprocessor.pl from your Mac. Then running the script again will download and install correct gas-preprocessor.
