### ISSUE TITLE
missing libpostproc.a

### ISSUE THREAD

**Issue by frakman1** [kewlbear/FFmpeg-iOS-build-script#35]
I am trying to build iFrameExtractor and it instructs the user to first build ffmpeg and use the resultant libraries in its project. I used your build script and although it built most of the libraries, it is missing libpostproc.a. How do I go about building that? 

https://github.com/PinkyJie/iFrameExtractor

**Comment by kewlbear** [comment]
Looks like postproc requires GPL. So you should add --enable-gpl to CONFIGURE_FLAGS.

**Comment by frakman1** [comment]
Do you mean on line 16 of build-ffmpeg.sh:
from:
```
CONFIGURE_FLAGS="--enable-cross-compile --disable-debug --disable-programs \
                 --disable-doc --enable-pic"
```
to:
```
CONFIGURE_FLAGS="--enable-cross-compile --disable-debug --disable-programs \
                 --disable-doc --enable-pic --enable-gpl"
```

**Comment by kewlbear** [comment]
You're right. I'm not sure about your second question. I usually try running my script again. If that doesn't work, do "rm -rf scratch thin" and try again.

**Comment by frakman1** [comment]
Re-running the script worked. Thank you!
