### ISSUE TITLE
Works lfawlessly, but then how do you include FFmpeg in an existing project

### ISSUE THREAD

**Issue by JKalash** [kewlbear/FFmpeg-iOS-build-script#36]
I followed the steps and built ffmpeg for armv7 and arm64. 

How do you include FFmpeg in your project ? 

Any use case example would be great.

Thanks!

**Comment by Ewg777** [comment]
If you prefer Cocoapods
pod "FFmpegBin", :podspec => "https://gist.githubusercontent.com/Ewg777/0c55c438f13440350a61/raw/e3bf3118eae5281370301a5567bc4d2f287e383f/FFmpegBin.podspec"
or download this podspec into your local folder.

**Comment by kewlbear** [comment]
You should add libraries to your project and add include directory to header search path.
