### ISSUE TITLE
Trimming remote file

### ISSUE THREAD

**Issue by VicenteFava** [kewlbear/FFmpeg-iOS-build-script#38]
ffmpeg -i http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_50mb.mp4 -ss 00:01:08 -t 00:01:18 -async 1 cut.mp4

Hello,
The above command seems to do what I need (trim a remote video file and save the results locally). 
I need to do this on my iPhone but I could not use the library. The documentation is very obscure.

Can anyone help me?
Thanks

**Comment by Pranoy1c** [comment]
were you able to figure it out? I am trying to run a similar command from iOS but no idea how to interact with the library after successfully importing it.

**Comment by kewlbear** [comment]
You can always see the source ffmpeg.c. By the way closing this issue because it's not directly about the build script itself.

**Comment by mroushdy** [comment]
was anyone able to find a demo that does this on iOS?
