### ISSUE TITLE
libavutil.a(dict.o)' does not contain bitcode

### ISSUE THREAD

**Issue by Ewg777** [kewlbear/FFmpeg-iOS-build-script#40]
'libavutil.a(dict.o)' does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
When I use a binary for FFmpeg 2.7.2

**Comment by kewlbear** [comment]
According to http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled. You can enable botched by supplying `-fembed-bitcode` to CFLAGS at line 93. I will update the script soon.

**Comment by Ewg777** [comment]
Please update the script

**Comment by Ewg777** [comment]
Has binary for FFmpeg 2.7.2 release at sourceforge.net been updated?

**Comment by kewlbear** [comment]
The binary is automatically built using Travis CI. However Travis CI does not provide Xcode 7 yet. If you need a binary with botched now, you should build it yourself.

**Comment by Ewg777** [comment]
http://blog.travis-ci.com/2015-08-27-xcode-70-beta-for-oss/

**Comment by kewlbear** [comment]
Didn't know that. Will try when I get to work. Thanks for the info.

**Comment by Ewg777** [comment]
Really works, awesome! Thanks

**Comment by kewlbear** [comment]
Glad I could help.
