### ISSUE TITLE
libavutil.a(dict.o), building for tvOS, but linking in object file built for iOS, for architecture arm64

### ISSUE THREAD

**Issue by adcloeshelle** [kewlbear/FFmpeg-iOS-build-script#45]
Any thoughts on adding tvOS support?

**Comment by kewlbear** [comment]
Just checked with Xcode 7.1 beta 3 simulator. My test app builds and runs successfully, with many warnings though. I don't own an apple TV, so I don't know if it doesn't work for real device. Anyway I will look into getting rid of the warnings.

**Comment by kewlbear** [comment]
Added experimental script for tvOS. Please try it and let me know if it works.

**Comment by geoffheatley** [comment]
I'm still getting warnings Xcode 7.1 GM tvOS Simulator
eg;
ld: warning: URGENT: building for tvOS simulator, but linking in object file (/Projects/BlaBla/DerivedData/BlaBla/Build/Products/Debug-appletvsimulator/libBlaBla.a(af_volume.o)) built for (unknown). Note: This will be an error in the future.

**Comment by kyvu** [comment]
I'm also getting the same thing. Any ideas?

**Comment by geoffheatley** [comment]
No, just looking it at right this second. Banging my head aganst the wall. Trying to deploy to the AppleTV device now. Compliaing about no Arm64 symbols defined etc.

**Comment by geoffheatley** [comment]
Have even just included the thin Arm64 libs to try to pinpoint things. Throws up a bunch of errors like:

Undefined symbols for architecture arm64:
  "_av_frame_unref", referenced from:
      -[AudioDecoder audioUnitCallback:timestamp:busNumber:numberFrames:data:] in libArcPlayer.a(AudioDecoder.o)

Which is a symbol defined in libavutil.a which has definitely been build for Arm64 by the build script. Not sure why this is happening. Has it really been built for Arm64?

**Comment by jhays** [comment]
Just want to report that I had success compiling this using the tvOS build script and streaming an rtsp link on a tvOS physical device. 

Thanks!

**Comment by kewlbear** [comment]
Great news! Thanks for reporting.

**Comment by mooncatventures-group** [comment]
jays did you have to do anything special to get this to compile under TVOS, as for the licensing  question that was raised on reddit, there are we've used ffmpeg based RTSP players in apps that are in the app store on a number of commercial  products we've had no issues getting them approved. with the introduction of video toolbox we stop supporting streammoreplay which was the commercial version of our ffmpegdecoder library. but TVOS doesn't support video toolbox except via private headers that won't make it into the App Store. my suspicion is that apple will eventually support it on TVOS . hope I answered some of your questions. mc mooncatventures LLC
