### ISSUE TITLE
iOS build for ffmpeg 2.8.1

### ISSUE THREAD

**Issue by subashw** [kewlbear/FFmpeg-iOS-build-script#46]
Hi

I found that the build does not have any of the muxers for example mpegts in the build.  Is this by accident or by design.  I tried building it using your shell script by adding configuration option --enable_muxers but no change. How do I get muxers into the build?

**Comment by kewlbear** [comment]
Muxers are in libavformat.a. You can also see config.log for the list of muxers built.
