### ISSUE TITLE
xcrun -sdk iphoneos clang is unable to create an executable file.

### ISSUE THREAD

**Issue by iraj-wisilica** [kewlbear/FFmpeg-iOS-build-script#48]
xcrun -sdk iphoneos clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

**Comment by kewlbear** [comment]
Please attach config.log file.

**Comment by iraj-wisilica** [comment]
Thank you for your response, Kewlbear. I had some issues with my Xcode path and fixed it.

**Comment by kewlbear** [comment]
You're welcome.
