### ISSUE TITLE
Xcode7.1 compile FFmpeg with fdk-aac error

### ISSUE THREAD

**Issue by BossKing** [kewlbear/FFmpeg-iOS-build-script#52]
i use the build-fdk-aac.sh(ARCHS="armv7 x86_64 i386")/build-ffmpeg.sh(ARCHS="x86_64 i386 armv7") compile success,but i copy the  fdk-aac-ios to subdir of FFmpeg-iOS-build-script-master,it occurs error:
clang: warning: -framework ApplicationServices: 'linker' input unused
/var/folders/c5/pfgchldj5cg2xsldxgwr69940000gn/T/ffconf.xKkLU2f6.c:1:10: fatal error: 'ApplicationServices/ApplicationServices.h' file not found
#include <ApplicationServices/ApplicationServices.h>
         ^
1 error generated.
check_pkg_config fdk-aac fdk-aac/aacenc_lib.h aacEncOpen
pkg-config --exists --print-errors fdk-aac
Package fdk-aac was not found in the pkg-config search path.
Perhaps you should add the directory containing `fdk-aac.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fdk-aac' found
clang: warning: argument unused during compilation: '-pthread'
ld: warning: object file (/Users/apple/Desktop/GitHub/BKFFmpeg/FFmpeg-iOS-build-script-master/fdk-aac/lib/libfdk-aac.a(aacenc_lib.o)) was built for newer iOS version (9.1) than being linked (6.0)
ld: '/Users/apple/Desktop/GitHub/BKFFmpeg/FFmpeg-iOS-build-script-master/fdk-aac/lib/libfdk-aac.a(aacenc_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: libfdk_aac not found

**Comment by BossKing** [comment]
the kdf

**Comment by BossKing** [comment]
I would appreciate it for your help!

**Comment by kewlbear** [comment]
You can remove -fembed-bitcode flag from build-ffmpeg.sh. However, you will need arm64 support if you intend to sell your app through AppStore but fdk-aac is not ported to arm64 yet. Although you can build fdk-aac for arm64 specifying other ARM cpu, you should thoroughly test your app on real arm64 devices.

**Comment by BossKing** [comment]
thank you,I will try it!

发自我的 iPhone

**Comment by BossKing** [comment]
it works fine,you mean that if i want to supprot arm64,i can't compile FFmpeg with fdk-aac,i found the lastest verson is 0.1.4,i don't know if it supports arm64,another question is if i use Xcode7.1 with SDK9.1,the DEPLOYMENT_TARGET="9.1" in build-ffmpeg.sh,am i right?

**Comment by kewlbear** [comment]
You can build fdk-aac for arm64. But it doesn't use full power of 64-bit capability, because it's not ported. Deployment target means the lowest supported version.

**Comment by BossKing** [comment]
Thank you for your help!

发自我的 iPhone
