### ISSUE TITLE
Bad_access with latest static libraries version ffmpeg 2.8.2 avcodec.a

### ISSUE THREAD

**Issue by irfangul10pearls** [kewlbear/FFmpeg-iOS-build-script#53]
I have an app, In which I am decoding video frames coming from ip camera, but the method avcodec_decode_video2(m_pCodecCtx, m_pFrame, &consumed_bytes, &avpkt); present in avcodec.h/ avcodec.a generating bad_access. 

It was working fine with older version of static libraries but when i updated it to give my app support for arm64, its crashing with bad_access.

here crash log
[kisafa  22-11-2015, 12-19 PM.txt](https://github.com/kewlbear/FFmpeg-iOS-build-script/files/45471/kisafa.22-11-2015.12-19.PM.txt)

here is snapshot:
![vidin](https://cloud.githubusercontent.com/assets/7964039/11435909/0f3dd056-9501-11e5-9b9c-bee5f1f7801a.png)

This is SO link to the issue.
http://stackoverflow.com/questions/33941165/error-while-decoding-camera-stream-video-frame-using-ffmpeg-ios

**Comment by kewlbear** [comment]
Need more info. Simple test project to reproduce the issue would be best. Maybe you need to modify your code to properly support arm64.
