### ISSUE TITLE
Supporting about compile with lame

### ISSUE THREAD

**Issue by DickyT** [kewlbear/FFmpeg-iOS-build-script#54]
Hi, I was trying to build ffmpeg with `--enable-libmp3lame`, and I have no idea how to use your lame build script with this ffmpeg build script.

Thank you very much

**Comment by kewlbear** [comment]
Build lame first. When you use --enable-libXXX, you also need to provide paths to find the lib using -I and -L flags. See X264 in the script for example.

**Comment by DickyT** [comment]
Oh thank you very much!!! I am going to have a try this night!!

2015-12-03 19:43 GMT-04:00 Changbeom Ahn <notifications@github.com>:

**Comment by DickyT** [comment]
@kewlbear Hi, I just try it, and my `CFLAGS` is

`-arch arm64 -mios-version-min=6.0 -fembed-bitcode -I /Users/KanzakiMirai/XcodeProjects/ffmpeg-objc/FFMP3/lame-ios-build/fat-lame/include`

but the compiler still throws an error that `ERROR: libmp3lame >= 3.98.3 not found`, any idea about this?
Thank you very much!

**Comment by kewlbear** [comment]
I think it's related to bitcode. You should either remove -fembed-bitcode from this script or add it to lame script.

**Comment by DickyT** [comment]
Thank you very much!! I can make it work now!!!

**Comment by DickyT** [comment]
@kewlbear I got a new issue... While I am running on my simulator, XCode tells me.
![screen shot 2015-12-03 at 22 17 15](https://cloud.githubusercontent.com/assets/4535844/11580264/cf799f3a-9a0b-11e5-87b1-dc150e9115ed.png)

And I also tried disabling bitcode for both lame and ffmpeg, or enabing bitcode for them. Is this the problem that something goes wrong of lame? Thanks!!

**Comment by kewlbear** [comment]
Did you link lame to your app?

**Comment by DickyT** [comment]
Oh I even forget that, now I can run it on my simulator. Thank you very much!!!!

**Comment by Vetagiri-Hrushikesh** [comment]
> arm64



> @kewlbear Hi, I just try it, and my `CFLAGS` is
> 
> `-arch arm64 -mios-version-min=6.0 -fembed-bitcode -I /Users/KanzakiMirai/XcodeProjects/ffmpeg-objc/FFMP3/lame-ios-build/fat-lame/include`
> 
> `LDFLAGS` is
> 
> `-arch arm64 -mios-version-min=6.0 -fembed-bitcode -L /Users/KanzakiMirai/XcodeProjects/ffmpeg-objc/FFMP3/lame-ios-build/fat-lame/lib`
> 
> but the compiler still throws an error that `ERROR: libmp3lame >= 3.98.3 not found`, any idea about this?
> Thank you very much!

Can you please show me how to did you added those flags in your file. I tried the same but Iam ending with this -> 
`ERROR: libmp3lame >= 3.98.3 not found`
