### ISSUE TITLE
Could not build with librtmp

### ISSUE THREAD

**Issue by samwize** [kewlbear/FFmpeg-iOS-build-script#55]
I am trying to build with rtmp support, but encountered the error:

    ERROR: librtmp not found using pkg-config

My steps to building ffmpeg with rtmp:

- Build rtmp using https://github.com/saiten/ios-librtmp
- Add `--enable-librtmp` to CONFIGURE_FLAGS
- Add `export PKG_CONFIG_PATH="/tmp/librtmp-$ARCH/lib/pkgconfig"`

Will appreciate help on this. Thanks.

**Comment by kewlbear** [comment]
I guess you need to add -I<librtmp include path> and -L<librtmp library path> to CFLAGS and LDFLAGS respectively.

**Comment by samwize** [comment]
I did add them too. Forgot to mention.

    EXTRA_CFLAGS="$EXTRA_CFLAGS -I/tmp/librtmp-$ARCH/include"
    EXTRA_LDFLAGS="$EXTRA_LDFLAGS -L/tmp/librtmp-$ARCH/lib"

Still, it didn't work :(

**Comment by samwize** [comment]
I looked at `config.log` and turned out it is not finding ssl library.

Added openssl to `CFLAGS` and `LDFLAGS` and is building now.

Thanks!
