### ISSUE TITLE
libavcodec/avcodec.h file not found

### ISSUE THREAD

**Issue by jassadakorn** [kewlbear/FFmpeg-iOS-build-script#56]
Can you help me resolve this issue ?
Thank you

**Comment by kewlbear** [comment]
You should add include directory to "header search path".

**Comment by codebreaker5163** [comment]
Not working even after adding 'Header search path' = ./VideoKit/3rd-party/ffmpeg/include , also in your documentation you asked to delete the include folder in 3rd-party/ffmpeg folder and openSSL folder  , so the include folder does not exist at all

**Comment by kewlbear** [comment]
I don't understand which documentation you are referring to.  Anyway, you should use the path for "FFmpeg-iOS/include", not the *include" directory of FFmpeg source.
