### ISSUE TITLE
How to add https protocol support?

### ISSUE THREAD

**Issue by cuishengli** [kewlbear/FFmpeg-iOS-build-script#57]
I want to compile ffmpeg with ssl support,  in Mac OS X EI Capitan, when I use original configure file for compiling, the input like this:
    ./configure --prefix=/usr/local/ffmpeg --enable-protocol=https --enable-gnutls
and again, I want to use this script to compile library which compatible with iOS simulator and iPhone, I add "--enable-protocol=https --enable-gnutls" options to $CONFIGURE_FLAGS above ARCHS="arm64 armv7 x86_64 i386" statement, that is, changed the script file as below:
     .....
     CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-protocol=https --enable-gnutls"
     ARCHS="arm64 armv7 x86_64 i386"
    ......
 but the output is like below:
    building arm64...
    ERROR: gnutls not found using pkg-config
but when not using the script, just compile using configure file, there is no problem. I don't know why? can you help me to solve this problem? thanks!

**Comment by kewlbear** [comment]
I guess you need to compile gnutls for iOS and add to CFLAGS and LDFLAGS.
