### ISSUE TITLE
Compile FFmpeg with x264 error

### ISSUE THREAD

**Issue by devillee** [kewlbear/FFmpeg-iOS-build-script#59]
I've built everything correctly however I'm getting final build error in my app.
like:
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
Undefined symbols for architecture arm64:
  "_x264_encoder_open_148", referenced from:
      _X264_init in libavcodec.a(libx264.o)
  "_VTDecompressionSessionWaitForAsynchronousFrames", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionInvalidate", referenced from:
      _av_videotoolbox_default_free in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionDecodeFrame", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionCreate", referenced from:
      _av_videotoolbox_default_init2 in libavcodec.a(videotoolbox.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Did I make anything wrong ?  Hope for your answer,Thank you!

**Comment by kewlbear** [comment]
Seems like you didn't link with x264 and videotoolbox libraries to your app.

**Comment by devillee** [comment]
Yes , it's my problem, now it have fixed, Building FFmpeg with x264 is no problem, but when using FFmpeg to decode H.264 frame by frame , I got nothing in my app , I'am totally refer to decoding_encoding example in FFmpeg source code,Can you give me some advice about this,Thanks a lot.

**Comment by kewlbear** [comment]
You better ask stackoverflow.
