### ISSUE TITLE
ffmpeg complication error - ERROR: libfdk_aac not found

### ISSUE THREAD

**Issue by divyamML** [kewlbear/FFmpeg-iOS-build-script#61]
eacmv_decoder
eamad_decoder
eatgq_decoder
eatgv_decoder
eatqi_decoder
eightbps_decoder
eightsvx_exp_decoder
eightsvx_fib_decoder
escape124_decoder
escape130_decoder
exr_decoder
ffv1_decoder
ffvhuff_decoder
fic_decoder
flashsv_decoder
flashsv2_decoder
flic_decoder
flv_decoder
fourxm_decoder
fraps_decoder
frwu_decoder
g2m_decoder
gif_decoder
h261_decoder
h263_decoder
h263i_decoder
h263p_decoder
h264_decoder
h264_crystalhd_decoder
h264_mmal_decoder
h264_qsv_decoder
h264_vda_decoder
h264_vdpau_decoder
hap_decoder
hevc_decoder
hevc_qsv_decoder
hnm4_video_decoder
hq_hqa_decoder
hqx_decoder
huffyuv_decoder
idcin_decoder
:1
# /Users/divyam/FFmpeg-iOS-build-script/ffmpeg-2.8/configure --target-os=darwin --arch=arm64 --cc='xcrun -sdk iphoneos clang' --enable-cross-compile --disable-debug --disable-programs --disable-doc --enable-pic --enable-gpl --enable-libx264 --enable-nonfree --enable-libfdk-aac --extra-cflags='-arch arm64 -mios-version-min=7.0 -fembed-bitcode -I/Users/divyam/FFmpeg-iOS-build-script/x264-ios/x264-iOS/include -I/Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/include' --extra-ldflags='-arch arm64 -mios-version-min=7.0 -fembed-bitcode -L/Users/divyam/FFmpeg-iOS-build-script/x264-ios/x264-iOS/lib -L/Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/lib' --prefix=/Users/divyam/FFmpeg-iOS-build-script/thin/arm64
ALL_COMPONENTS='
    aac_adtstoasc_bsf
chomp_bsf
dump_extradata_bsf
h264_mp4toannexb_bsf
hevc_mp4toannexb_bsf
imx_dump_header_bsf
mjpeg2jpeg_bsf
mjpega_dump_header_bsf
mp3_header_decompress_bsf
mpeg4_unpack_bframes_bsf
mov2textsub_bsf
noise_bsf
remove_extradata_bsf
text2movsub_bsf
    aasc_decoder
aic_decoder
alias_pix_decoder
amv_decoder
anm_decoder
ansi_decoder
apng_decoder
asv1_decoder
asv2_decoder
aura_decoder
aura2_decoder
avrp_decoder
avrn_decoder
avs_decoder
avui_decoder
ayuv_decoder
bethsoftvid_decoder
bfi_decoder
bink_decoder
bmp_decoder
bmv_video_decoder
clang: warning: argument unused during compilation: '-pthread'
ld: warning: ignoring file /Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/lib/libfdk-aac.a, missing required architecture arm64 in file /Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/lib/libfdk-aac.a (4 slices)
Undefined symbols for architecture arm64:
  "_aacEncOpen", referenced from:
      _check_aacEncOpen in ffconf.V1Eie6Py.o
     (maybe you meant: _check_aacEncOpen)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
check_lib fdk-aac/aacenc_lib.h aacEncOpen -lfdk-aac
check_header fdk-aac/aacenc_lib.h
check_cpp
BEGIN /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.14mpkUjJ.c
    1   #include <fdk-aac/aacenc_lib.h>
    2   int x;
END /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.14mpkUjJ.c
xcrun -sdk iphoneos clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPIC -arch arm64 -mios-version-min=7.0 -fembed-bitcode -I/Users/divyam/FFmpeg-iOS-build-script/x264-ios/x264-iOS/include -I/Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/include -std=c99 -fomit-frame-pointer -fPIC -pthread -E -o /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.V1Eie6Py.o /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.14mpkUjJ.c
check_func aacEncOpen -lfdk-aac
check_ld cc -lfdk-aac
check_cc
BEGIN /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.14mpkUjJ.c
    1   extern int aacEncOpen();
    2   int main(void){ aacEncOpen(); }
END /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.14mpkUjJ.c
xcrun -sdk iphoneos clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPIC -arch arm64 -mios-version-min=7.0 -fembed-bitcode -I/Users/divyam/FFmpeg-iOS-build-script/x264-ios/x264-iOS/include -I/Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/include -std=c99 -fomit-frame-pointer -fPIC -pthread -c -o /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.V1Eie6Py.o /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.14mpkUjJ.c
xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=7.0 -fembed-bitcode -L/Users/divyam/FFmpeg-iOS-build-script/x264-ios/x264-iOS/lib -L/Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/lib -Wl,-dynamic,-search_paths_first -o /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.9xtsDI52 /var/folders/f3/8phk_d4j5cj1lgvn7t_qbhjc0000gn/T/ffconf.V1Eie6Py.o -lfdk-aac -lm -lbz2 -lz -pthread
clang: warning: argument unused during compilation: '-pthread'
ld: warning: ignoring file /Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/lib/libfdk-aac.a, missing required architecture arm64 in file /Users/divyam/FFmpeg-iOS-build-script/fdk-aac/fdk-aac-ios/lib/libfdk-aac.a (4 slices)
Undefined symbols for architecture arm64:
  "_aacEncOpen", referenced from:
      _main in ffconf.V1Eie6Py.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: libfdk_aac not found

**Comment by kewlbear** [comment]
My fdk-aac build script does not include arm64. Please see #52 .
