### ISSUE TITLE
ERROR: libx264 not found

### ISSUE THREAD

**Issue by Abson** [kewlbear/FFmpeg-iOS-build-script#62]
When i open X264=`pwd`/fat-x264 want to compile the ffmepg, there are something worng

<img width="459" alt="2016-03-24 3 24 29" src="https://cloud.githubusercontent.com/assets/13198014/14010893/88645678-f1d4-11e5-993c-648751a55b36.png">

I have no idea to fix it.....

**Comment by Abson** [comment]
oh, this all my fault, i have not compile the x264, i am so sorry

**Comment by kewlbear** [comment]
You are welcome.
