### ISSUE TITLE
Compile Error when using Objetive-C++

### ISSUE THREAD

**Issue by paszoujp** [kewlbear/FFmpeg-iOS-build-script#63]
When I change my file name xx.m  into xx.mm , in order to compile the source as Objetive-c++, all the functions I used has a 'symbol(s) not found for architecture x86_64" problem. 
I don't know how to fix it.

'

**Comment by kewlbear** [comment]
You should provide more info like complete error messages. But I guess you can workaround by wrapping `#include`s with `extern "C"` like below.

```
...
extern "C" {
  #include "libavcodec/avcodec.h"
}
...
```
