### ISSUE TITLE
Compile with error

### ISSUE THREAD

**Issue by NoWall57** [kewlbear/FFmpeg-iOS-build-script#64]
Hi,when I run ./build-ffmpeg.sh lipo,I met a error 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified
I have searched in Goolge,but there is something wrong with my key words or there is no solution.

**Comment by kewlbear** [comment]
Looks like you didn't build for each architectures first. Just run the script without any parameters. Then it will build for each architectures and run `lipo` automatically.

**Comment by NoWall57** [comment]
Thanks a lot! : )

**Comment by kewlbear** [comment]
You are welcome.
