### ISSUE TITLE
Help with finding an FFmpeg Demo project

### ISSUE THREAD

**Issue by mroushdy** [kewlbear/FFmpeg-iOS-build-script#65]
I can't seem to find an FFmpeg demo project that doesnt have most functions deprecated. Does anyone have resources? I am new to FFmpeg and my C++ is pretty basic so it's hard for me to get a start on FFmpeg.

**Comment by kewlbear** [comment]
What do you want to do?

**Comment by mroushdy** [comment]
I am trying to cut a portion out of a remote file based on a certain time.

**Comment by kewlbear** [comment]
You should see https://ffmpeg.org/doxygen/trunk/remuxing_8c-example.html and other examples in that directory. If you change main to something else (like ExampleMain), you can try the code in your app. It's much more complex but you should also study https://ffmpeg.org/doxygen/trunk/ffmpeg_8c.html for detailed cutting logic.
