### ISSUE TITLE
No H264 encoder?

### ISSUE THREAD

**Issue by coollofty** [kewlbear/FFmpeg-iOS-build-script#68]
av_register_all();
AVCodec* pCodec = avcodec_find_encoder(AV_CODEC_ID_H264);
assert(pCodec);   // it is asseted....

-----------------------------
But I found the MPEG4 is avaiabled

**Comment by kewlbear** [comment]
See scratch/<arch>/config.log for configured codecs. Maybe you need to configure FFmpeg to use x264.
