### ISSUE TITLE
Can I use this for MAC OS X?

### ISSUE THREAD

**Issue by cmario92** [kewlbear/FFmpeg-iOS-build-script#70]
Hi there,
Appreciate what you are doing here.

I was wondering if I can use this library for my MAC OS X in XCode.

If it works for Mac OS X I can then add it to my swift project using an objective-c bridge to link the library with my project

**Comment by kewlbear** [comment]
You don't need this for OS X. You just `./configure; make install` on OS X.

**Comment by cmario92** [comment]
What do you mean I do not need this in Mac OS X?Can you explain why is that?

**Comment by kewlbear** [comment]
Yes you don't need it. Because FFmpeg builds just fine for OS X out of the box.

**Comment by cmario92** [comment]
Thanks for the reply, sorry for the delay.
I know I can use FFMPEG through the Mac's terminal, but the question here is how to add the library to Xcode and use it in my project?

**Comment by kewlbear** [comment]
1. download FFmpeg source and unarchive
2. in the source directory, `./configure; make install`
3. in Xcode add the directories to header/library search paths

I didn't try above steps myself.
For more questions regarding FFmpeg and OS X, you should ask somewhere else like stackoverflow.
