### ISSUE TITLE
Correctly Linking Libraries

### ISSUE THREAD

**Issue by AlecGamble** [kewlbear/FFmpeg-iOS-build-script#71]
Hi Kewlbear,

Firstly thank you so much for making these ffmpeg libraries so accessible. I'm fairly new to software development and I'm trying to include them in my iOS project. It's a cordova application but I don't think that's really relevant to the issue I'm having.

My file structure is like this:

```
-iOS (folder)
   -App.xcodeproj
   -App (folder)
      -Classes (folder)
      -ffmpeg-ios-master (folder)
         -FFmpeg-iOS (folder)
            -inlcude (folder)
            -lib (folder)
         -ffmpeg-3.0 (folder)
         -scratch (folder)
```
So the path to the include would be iOS/App/ffmpeg-ios-master/FFmpeg-iOS/include. So I'm trying to use the avcodec and swscale libraries in my project.

I've added to "Link Binary With Libraries" all of the .a files and I've also added "$(SRCROOT)/App/ffmpeg-ios-master/FFmpeg-iOS/include" to the header search paths.

I'm wondering what I'm missing or have done wrong though because I'm getting: Linker command failed with exit code 1.

Is it obvious what I'm doing wrong or have missed out?

**Comment by kewlbear** [comment]
You should link with libiconv, libz, libbz2.
