### ISSUE TITLE
包大小的问题

### ISSUE THREAD

**Issue by goodcyg** [kewlbear/FFmpeg-iOS-build-script#73]
首先感谢楼主的分享。但是我在实际遇到一个问题，希望楼主指点一下，我需要在iOS下支持win下的rmvb，avi，asf等格式，因此我编译出来的包有385M，而我看到一款app，也能播放同样的win下的格式，而它的大小才11M，iOS原生库是不支持的。请问楼主，他是用啥技术实现的？

**Comment by kewlbear** [comment]
Sorry I can't read Chinese.  Tried using Google translate, but I can't understand the translation.

**Comment by goodcyg** [comment]
Thanks for sharing. But I encountered in practice a problem, hope Louzhu pointing out, I need to win support in IOS, avi, ASF format, so I compiled package has 385M. And I see a app, also can play the same win format, and its size to 11m, IOS native libraries is unsupported. I would like to ask the landlord, he is using what technology to achieve?

**Comment by kewlbear** [comment]
You can choose which formats/codecs to support by changing CONFIGURE_FLAGS.  Supporting less will decrease your app size.  But 385M seems to big.  Libraries built by the script is about 136M.  Are you embedding sample video by mistake?

**Comment by goodcyg** [comment]
I use the default configuration script package, the package is much smaller, but play the same video, the video quality is very vague, which is why? 385m library playback video is very clear?

**Comment by kewlbear** [comment]
What is this 385m library?  Did you compile it yourself, or got it precompiled?

**Comment by goodcyg** [comment]
I'm using this（https://github.com/Bilibili/ijkplayer） open source library.ompile iOS version，using ijkplayer/config/module-default.sh ，Compiled static library。I guess that is a compilation of macro definition is not the same, but why do you compile the library to play the same video is very vague. Can compile the library, the video seems to be very clear? Thank you

**Comment by kewlbear** [comment]
I have some questions:

1. Did you change only the FFmpeg library?  (Are you using the same rendering code?)
1. What is the video?  Can I access it?
1. Which devices/simulators did you test on?
1. Which version of Xcode do you use?

**Comment by goodcyg** [comment]
1.Both are the same ffmpeg-3.1.1
2.You can not visit, is to convert some of the video, with the video, in between them play, do the contrast to see the effect. You can also get some video compared to see the effect.
3.test on iphone 6 plus 
4.xcode 7.2.1

**Comment by goodcyg** [comment]
1.Both are the same ffmpeg-3.1.1
2.You can not visit, is to convert some of the video, with the video, in between them play, do the contrast to see the effect. You can also get some video compared to see the effect.
3.test on iphone 6 plus 
4.xcode 7.2.1

**Comment by Shun87** [comment]
Why there is no arm7s cpu arch?
