### ISSUE TITLE
Some Error With "Symbol(s) not found"

### ISSUE THREAD

**Issue by GintokiS** [kewlbear/FFmpeg-iOS-build-script#74]
This is the first time I use FFmpeg. I download the lib use this url https://downloads.sourceforge.net/project/ffmpeg-ios/ffmpeg-ios-master.tar.bz2. After download I add the "include" and "lib" folder in xcode, create a .mm class, include avformat.h and call avformat_version(); in a method to test.At last the error "Symbol(s) not found" occur. I used all simulators and my iPhone 5, xcode shown me "symbol(s) not found for architecture" armv7, i386, x86_64.
Anyone can help me? Thanks a lot!

**Comment by kewlbear** [comment]
Wrap `#include`s of FFmpeg headers with `extern "C" {` and `}`.  Like:

```
extern "C" {
#include "libavcodec/avcodec.h"
// ...
}
```

**Comment by GintokiS** [comment]
Well, I found that the error will occur when I call avformat_version() or av_register_all(). I copy the lib files to a well-run project and no error. So I guess if these methods had removed or not.

**Comment by kewlbear** [comment]
Have you tried my suggestion?  If you are using C++ (.mm), you need it.

**Comment by GintokiS** [comment]
@kewlbear So sorry that I did not try your suggestion. But now it works well. Thanks a lot! ^ ^

**Comment by GintokiS** [comment]
@kewlbear So sorry that I did not try your suggestion. But now it works well. Thanks a lot! ^ ^

**Comment by Vienta** [comment]
@GintokiS How did you solved this?

**Comment by kewlbear** [comment]
@Vienta Please try my suggestion above.

**Comment by Vienta** [comment]
@kewlbear  
I'v tried.Worked for me.Thank you very much!

**Comment by ZvOlCuOk2009** [comment]
I also have an error when calling the function av_register_all () and other functions ffmpeg. If I do not call the library function, the project is compiled normally.  But the solution is with the file extension to mm. under C ++ does not help..(

**Comment by kewlbear** [comment]
@ZvOlCuOk2009 Actually the solution is for C++. It's a general solution for using C libraries with C++.

**Comment by ZvOlCuOk2009** [comment]
This is the description of my error the xcode: "Undefined symbols for architecture i386:
  "av_register_all()", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)". I understand that he does not see the library architecture for running the application in the simulator. But I tried a lot of solutions and nothing helped me.

**Comment by kewlbear** [comment]
First see if `file libavformat.a` command output contains 'i386'.  If it doesn't, you should build FFmpeg again including 'i386' architecture.

**Comment by ZvOlCuOk2009** [comment]
Thank you for the quick response!
Where exactly should the command "i386" be? At me file libavformat.а opens in the text editor with the ciphered unicode ...

**Comment by kewlbear** [comment]
In terminal app on your mac, enter "file libavformat.a" and hit enter.

**Comment by ZvOlCuOk2009** [comment]
I get such an answer in the terminal: MacBook-Pro-TS-Aleksander:com.partizandm.app.ios.gen2 admin$ cd /Users/admin/com.partizandm.app.ios.gen2 
MacBook-Pro-TS-Aleksander:com.partizandm.app.ios.gen2 admin$ file libavformat.a
libavformat.a: cannot open `libavformat.a' (No such file or directory)

**Comment by kewlbear** [comment]
Go to the directory containing that file before running the command obviously. Or you can drag the file from finder to terminal to enter the full path.

**Comment by ZvOlCuOk2009** [comment]
Such an answer in the terminal: libavformat.a: Mach-O universal binary with 4 architectures: [arm_v7: current ar archive random library] [i386] [x86_64] [arm64]
libavformat.a (for architecture armv7):	current ar archive random library
libavformat.a (for architecture i386):	current ar archive random library
libavformat.a (for architecture x86_64):	current ar archive random library
libavformat.a (for architecture arm64):	current ar archive random library

**Comment by ZvOlCuOk2009** [comment]
I thus checked all the libraries, they all contain the necessary architectures

**Comment by ZvOlCuOk2009** [comment]
Please, tell me what else can be the problem of compilation in my case?

**Comment by kewlbear** [comment]
Make sure Xcode is linking with those *.a files. You should see build log of your app.
