### ISSUE TITLE
Mac OSX build

### ISSUE THREAD

**Issue by king129** [kewlbear/FFmpeg-iOS-build-script#77]
How do I compile, can use the Mac OSX platform

**Comment by singcodes** [comment]
@king129 
You can download static build of ffmpeg for osx from [here](http://evermeet.cx/ffmpeg/)
or from [homebrew](http://brew.sh/)

**Comment by king129** [comment]
I386 x86_64 both architecture should be corresponding to the big Mac OSX both 32-bit and 64 - bit

Website provides the executable file In OSX platform As if can only be used to simulation terminal NSTask this

**Comment by rorlich** [comment]
How can i use this script to compile for OSX library which i can use from xcode ?

**Comment by kewlbear** [comment]
You don't need this script for macOS. Just do `./configure; make install`. You may need to install some tools though.

**Comment by king129** [comment]
@kewlbear @rorlich 
I use this (FFmpeg-iOS-build-script) script compile the i386 x86_64 
Then import Mac OSX project 
The project more successful compilation, and running
There was a problem but using ffmpeg decoding

```C
if (avformat_open_input(&pFormatCtx, [path UTF8String], NULL, NULL) != 0) {
        // This step would have failed video file is normal All can use in iOS ffmpeg decoding
        NSLog(@"Failed to open the file");
        return;
    }
```

**Comment by kewlbear** [comment]
It doesn't seem to be related with the script. But you should check error code.
