### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HEXUANDSDDFSD** [kewlbear/FFmpeg-iOS-build-script#80]
Undefined symbols for architecture x86_64:
  "av_register_all()", referenced from: 
Please tell me the reason

**Comment by HEXUANDSDDFSD** [comment]
![2016-08-23 8 39 55](https://cloud.githubusercontent.com/assets/21185598/17876493/3634d35e-690d-11e6-868f-f506c6358a28.png)
Those Library have been linked

**Comment by kewlbear** [comment]
Did you link `libavformat.a`?

**Comment by HEXUANDSDDFSD** [comment]
I have solved this problem. 
![2016-08-24 8 36 25](https://cloud.githubusercontent.com/assets/21185598/17914586/f46fdc4c-69d5-11e6-80dc-0544e788728f.png)
Thank you

**Comment by HEXUANDSDDFSD** [comment]
Are you good at FFmpeg？

**Comment by liwenDeng** [comment]
@HEXUANDSDDFSD  how do you solve this problem?  I have met the same problem.
