### ISSUE TITLE
why point out No such file or directory?

### ISSUE THREAD

**Issue by LuLoveMin** [kewlbear/FFmpeg-iOS-build-script#85]
./build-ffmpeg.sh: line 121: /Users/luheng/Desktop/FFmpeg-iOS-build-script/ffmpeg-3.2/configure:
No such file or directory

why point out this?

**Comment by kewlbear** [comment]
Maybe some issues with the download of FFmpeg source. Please remove ffmpeg-3.2 directory and try again.
