### ISSUE TITLE
/ffmpeg-3.2/configure: No such file or directory

### ISSUE THREAD

**Issue by appbanana** [kewlbear/FFmpeg-iOS-build-script#86]
I check it.But My FFmpeg-iOS-build-script  directory donot have ffmpeg file. I try again and has same issues. It print this text in the blow. How to solve?

FFmpeg source not found. Trying to download...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
building arm64...
./build-ffmpeg.sh: line 121: /Users/apple/Desktop/FFmpeg-iOS-build-script-master/ffmpeg-3.2/configure: No such file or directory

**Comment by kewlbear** [comment]
You could try downloading FFmpeg source yourself and let the script use it.

**Comment by appbanana** [comment]
It is probably the path of Xcode problem.Use this command can be solved in the below.
 sudo xcode-select -s /Applications/Xcode.app
