### ISSUE TITLE
libopencore_amrnb not found

### ISSUE THREAD

**Issue by sandyCK** [kewlbear/FFmpeg-iOS-build-script#88]
Thanks for your script!

I change your configuration to this "--enable-cross-compile --disable-debug --disable-programs --disable-doc --enable-pic  --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-version3 --enable-nonfree --disable-ffplay --disable-ffprobe --disable-ffserver --enable-shared --enable-static "(I want to add amr codec).   And the deployment target to 8.0.

Then I download the openjpeg 1.5.1 and put it to the corresponding /usr/loacl/bin(include)(lib).

However the error libopencore_amrnb not found  always exists! Could you point out what else should I do to compile ffmpeg with amr support? Thanks a lot!

**Comment by kewlbear** [comment]
If you want to use external libraries like amr codec, you should build it for iOS before FFmpeg. Then edit this script to pass necessary info like include/library path to `configure`.
