### ISSUE TITLE
error happened when compile arm64

### ISSUE THREAD

**Issue by liupeng-qiushibaike** [kewlbear/FFmpeg-iOS-build-script#91]
my xcode's version is 8.2.1

AS     	libavcodec/aarch64/fft_neon.o
1 warning generated.
warning: unknown warning option '-Wno-unused-const-variable'; did you mean '-Wno-unused-variable'? [-Wunknown-warning-option]
<stdin>:190:21: error: invalid operand for instruction
        tbl v4.16b, {v4.16b}, v30.16b
                    ^
<stdin>:191:21: error: invalid operand for instruction
        tbl v5.16b, {v5.16b,v6.16b}, v31.16b
                    ^
<stdin>:215:21: error: invalid operand for instruction
        tbl v4.16b, {v4.16b}, v30.16b
                    ^
<stdin>:216:21: error: invalid operand for instruction
        tbl v5.16b, {v5.16b,v6.16b}, v31.16b
                    ^
<stdin>:293:21: error: invalid operand for instruction
        tbl v4.16b, {v4.16b}, v30.16b
                    ^
<stdin>:294:21: error: invalid operand for instruction
        tbl v5.16b, {v5.16b,v6.16b}, v31.16b
                    ^
<stdin>:332:21: error: invalid operand for instruction
        tbl v4.16b, {v4.16b}, v30.16b
                    ^
<stdin>:333:21: error: invalid operand for instruction
        tbl v5.16b, {v5.16b,v6.16b}, v31.16b
                    ^
make: *** [libavcodec/aarch64/fft_neon.o] Error 1

**Comment by liupeng-qiushibaike** [comment]
I fixed it by changing DEPLOYMENT_TARGET from 6.0 to 8.0

**Comment by kewlbear** [comment]
Thanks for the info!
