### ISSUE TITLE
enable debug

### ISSUE THREAD

**Issue by weinixuehao** [kewlbear/FFmpeg-iOS-build-script#92]
1、I want to enable debug with symbols, how to do it?
2、if can not, alternatively print log in source code, but each time take much time to build.
has solution avoid it?

**Comment by kewlbear** [comment]
Try `configure --help`. There are options like following:

```
Developer options (useful when working on FFmpeg itself):
  --disable-debug          disable debugging symbols
  --enable-debug=LEVEL     set the debug level []
  --disable-optimizations  disable compiler optimizations
```
