### ISSUE TITLE
Contains AAC Error

### ISSUE THREAD

**Issue by Eafy** [kewlbear/FFmpeg-iOS-build-script#93]
Compiler hints：“ERROR: libfdk_aac not found”，But the path to the AAC library is correct, and the AAC library supports all platforms of iOS。
Please, where is the problem?

**Comment by Eafy** [comment]
I use fdk-aac-0.1.5，ffmpeg:3.2.4

**Comment by kewlbear** [comment]
You should show some error messages.

**Comment by Eafy** [comment]
#!/bin/sh

# directories
SOURCE="ffmpeg-3.2.4"
FAT="FFmpeg-iOS"

SCRATCH="scratch"
# must be an absolute path
THIN=`pwd`/"thin"

# absolute path to x264 library
X264=`pwd`/x264-iOS

FDK_AAC=`pwd`/fat-faac

--------------------------------

lzjMac:lib lzj$ lipo -info libfdk-aac.a 
Architectures in the fat file: libfdk-aac.a are: armv7 armv7s i386 arm64 

--------------------------------

lzjMac:FFmpeg-iOS-build-script-master lzj$ ./build-ffmpeg.sh 
building arm64...
ERROR: libfdk_aac not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

**Comment by kewlbear** [comment]
If you used my script to build fdk-aac, I've updated it to support bitcode. Or you can fix it yourself by adding `-fembed-bitcode` to `CFLAGS`.
