### ISSUE TITLE
How to add H265 / HEVC decoding library

### ISSUE THREAD

**Issue by memoryForever** [kewlbear/FFmpeg-iOS-build-script#95]
Compile the library without creating h265/HEVC decoder session

**Comment by kewlbear** [comment]
I googled "ffmpeg h265" and found https://trac.ffmpeg.org/wiki/Encode/H.265. It says you need `--enable-libx265`. You should build `x265` for iOS (or tvOS) first.

**Comment by memoryForever** [comment]
Ok, thank you very much, but you can add these steps to the script, I think many people will need it
