### ISSUE TITLE
Compress the stream when i stream a local file to rtmp server ?

### ISSUE THREAD

**Issue by dungeonsnd** [kewlbear/FFmpeg-iOS-build-script#96]
Hello,
I'm new to audio and video process. 

The following codes demonstrate how to stream a local file to rtmp server using ffmpeg in iOS platform. It can work successfully.

But the server received the raw video which has the same file size with the pusher.  I wanna to know how to compress or encode the raw video copied from iOS album to minimize the size. (I had tried to add encode code, but it has no effect.)

I know this is only a ffmpeg iOS build-script project, but it could be very helpful if you give me a tip.
Thanks for your help very much!

`

    + (void)streamVideo:(NSString*)inputFile
              outputUrl:(NSString*)outputUrl
          playFromTimer:(NSInteger)playFromTimer
               stopFlag:(NSInteger*)stopFlag{
        
        char input_str_full[1024]={0};
        char output_str_full[1024]={0};
        
        sprintf(input_str_full,"%s",[inputFile UTF8String]);
        sprintf(output_str_full,"%s",[outputUrl UTF8String]);
        
        AVOutputFormat *ofmt = NULL;
        //Input AVFormatContext and Output AVFormatContext
        AVFormatContext *ifmt_ctx = NULL, *ofmt_ctx = NULL;
        AVPacket pkt;
        char in_filename[500]={0};
        char out_filename[500]={0};
        int ret, i;
        int videoindex=-1;
        int frame_index=0;
        int64_t start_time=0;
        
        strcpy(in_filename,input_str_full);
        strcpy(out_filename,output_str_full);
        
        av_register_all();
        //Network
        avformat_network_init();
        //Input
        if ((ret = avformat_open_input(&ifmt_ctx, in_filename, 0, 0)) < 0) {
            printf( "Could not open input file.");
            goto end;
        }
        if ((ret = avformat_find_stream_info(ifmt_ctx, 0)) < 0) {
            printf( "Failed to retrieve input stream information");
            goto end;
        }
        
        for(i=0; i<ifmt_ctx->nb_streams; i++)
            if(ifmt_ctx->streams[i]->codec->codec_type==AVMEDIA_TYPE_VIDEO){
                videoindex=i;
                break;
            }
        printf("@@ videoindex=%d\n", ifmt_ctx->nb_streams);
        av_dump_format(ifmt_ctx, 0, in_filename, 0);
        
        //Output
        
        avformat_alloc_output_context2(&ofmt_ctx, NULL, "flv", out_filename); //RTMP
        //avformat_alloc_output_context2(&ofmt_ctx, NULL, "mpegts", out_filename);//UDP
        
        if (!ofmt_ctx) {
            printf( "Could not create output context\n");
            ret = AVERROR_UNKNOWN;
            goto end;
        }
        ofmt = ofmt_ctx->oformat;
        for (i = 0; i < ifmt_ctx->nb_streams; i++) {
            
            AVStream *in_stream = ifmt_ctx->streams[i];
            AVStream *out_stream = avformat_new_stream(ofmt_ctx, in_stream->codec->codec);
            if (!out_stream) {
                printf( "Failed allocating output stream\n");
                ret = AVERROR_UNKNOWN;
                goto end;
            }
            
            ret = avcodec_copy_context(out_stream->codec, in_stream->codec);
            if (ret < 0) {
                printf( "Failed to copy context from input to output stream codec context\n");
                goto end;
            }
            out_stream->codec->codec_tag = 0;
            if (ofmt_ctx->oformat->flags & AVFMT_GLOBALHEADER)
                out_stream->codec->flags |= CODEC_FLAG_GLOBAL_HEADER;
            
            
            //////////// added 2017-03-16, test compress, BUT has no effect. 测试视频编码压缩
            out_stream->codec->bit_rate =50*1024;
            out_stream->r_frame_rate.num = 5;
            out_stream->avg_frame_rate.num = 10;
            
            //////////// added 2017-03-16, test compress, BUT has no effect. 测试视频编码压缩
            //        out_stream->codec->global_quality =2;
            //        out_stream->codec->compression_level =0;
            //        out_stream->codec->bit_rate =50*1024;
            //
            //        int m_fps =10;
            //
            //        out_stream->codec->width =1280;
            //        out_stream->codec->height =720;
            //
            //        out_stream->codec->time_base.num = 41;
            //        out_stream->codec->time_base.den =
            //        m_fps*(in_stream->codec->ticks_per_frame);
            //        out_stream->time_base.num = 41;
            //        out_stream->time_base.den = 1000;
            //        out_stream->r_frame_rate.num = m_fps;
            //        out_stream->r_frame_rate.den = 1;
            //        out_stream->avg_frame_rate.den = 1;
            //        out_stream->avg_frame_rate.num = m_fps;
            ////////////
            
        }
        //Dump Format------------------
        av_dump_format(ofmt_ctx, 0, out_filename, 1);
        //Open output URL
        if (!(ofmt->flags & AVFMT_NOFILE)) {
            ret = avio_open(&ofmt_ctx->pb, out_filename, AVIO_FLAG_WRITE);
            if (ret < 0) {
                printf( "Could not open output URL '%s'", out_filename);
                goto end;
            }
        }
        
        ret = avformat_write_header(ofmt_ctx, NULL);
        if (ret < 0) {
            printf( "Error occurred when opening output URL\n");
            goto end;
        }
        
        
        ///  added 2017-03-16, 测试从某一时刻开始推流
        int64_t play_from_time =playFromTimer*1000*1000;
        int need_send =0;
        ///
        
        
        start_time=av_gettime();
        while (*stopFlag==1) {
            AVStream *in_stream, *out_stream;
            //Get an AVPacket
            ret = av_read_frame(ifmt_ctx, &pkt);
            if (ret < 0)
                break;
            //FIX：No PTS (Example: Raw H.264)
            //Simple Write PTS
            if(pkt.pts==AV_NOPTS_VALUE){
                //Write PTS
                AVRational time_base1=ifmt_ctx->streams[videoindex]->time_base;
                //Duration between 2 frames (us)
                int64_t calc_duration=(double)AV_TIME_BASE/av_q2d(ifmt_ctx->streams[videoindex]->r_frame_rate);
                //Parameters
                pkt.pts=(double)(frame_index*calc_duration)/(double)(av_q2d(time_base1)*AV_TIME_BASE);
                pkt.dts=pkt.pts;
                pkt.duration=(double)calc_duration/(double)(av_q2d(time_base1)*AV_TIME_BASE);
            }
            //Important:Delay
            if(pkt.stream_index==videoindex){
                AVRational time_base=ifmt_ctx->streams[videoindex]->time_base;
                AVRational time_base_q={1,AV_TIME_BASE};
                int64_t pts_time = av_rescale_q(pkt.dts, time_base, time_base_q);
                
                ///  added 2017-03-16, 测试从某一时刻开始推流
                int64_t now_time = av_gettime() - start_time;
                printf("== pts_time=%lld, now_time=%lld, play_from_time=%lld \n",
                       pts_time, now_time, play_from_time);
                
                if (pts_time>=play_from_time){
                    need_send =1;
                }
                
                if (pts_time > now_time+play_from_time) {
                    if (need_send) {
                        printf("++++ usleep %lld \n", pts_time - now_time -play_from_time);
                        av_usleep(pts_time - now_time -play_from_time);
                        printf("---- \n");
                    }
                }
            }
            
            in_stream  = ifmt_ctx->streams[pkt.stream_index];
            out_stream = ofmt_ctx->streams[pkt.stream_index];
            /* copy packet */
            //Convert PTS/DTS
            pkt.pts = av_rescale_q_rnd(pkt.pts, in_stream->time_base, out_stream->time_base, (AV_ROUND_NEAR_INF|AV_ROUND_PASS_MINMAX));
            pkt.dts = av_rescale_q_rnd(pkt.dts, in_stream->time_base, out_stream->time_base, (AV_ROUND_NEAR_INF|AV_ROUND_PASS_MINMAX));
            pkt.duration = av_rescale_q(pkt.duration, in_stream->time_base, out_stream->time_base);
            pkt.pos = -1;
            //Print to Screen
            if(pkt.stream_index==videoindex){
                printf("Send %8d video frames to output URL\n",frame_index);
                frame_index++;
            }
            
            
            ///  added 2017-03-16, 测试从某一时刻开始推流
            if (need_send)
                ret = av_interleaved_write_frame(ofmt_ctx, &pkt);
            
            
            if (ret < 0) {
                printf( "Error muxing packet\n");
                break;
            }
            
            av_free_packet(&pkt);
            
        }
        //写文件尾（Write file trailer）
        av_write_trailer(ofmt_ctx);
    end:
        avformat_close_input(&ifmt_ctx);
        /* close output */
        if (ofmt_ctx && !(ofmt->flags & AVFMT_NOFILE))
            avio_close(ofmt_ctx->pb);
        avformat_free_context(ofmt_ctx);
        if (ret < 0 && ret != AVERROR_EOF) {
            printf( "Error occurred.\n");
            return;
        }
        return;
        
    }

`

**Comment by kewlbear** [comment]
You should study https://ffmpeg.org/doxygen/trunk/doc_2examples_2transcoding_8c-example.html.

**Comment by dungeonsnd** [comment]
I really appreciate it.
I'll study that example.
