### ISSUE TITLE
Add image watermark for video，JPG is OK，bug PNG is no useful～

### ISSUE THREAD

**Issue by kangle1208** [kewlbear/FFmpeg-iOS-build-script#97]
Thank you for shareing!
But when I use it to add watermark for video
JPG image file is no problem, but PNG image file is no useful
I can't see any watermark on the video

And the last log is : **Generic error in an external library**

How can I change the build information to fix this problem?

Thank you very much!

**Comment by kewlbear** [comment]
Which FFmpeg function return the error code?

**Comment by kangle1208** [comment]
pngdec.c file - png_decode_idat func show log:  inflate returned error -3
and ffmpeg.c file - process_input_packet func show log:  Generic error in an external library

This link : [https://trac.ffmpeg.org/ticket/4822#no1](url) may be the same problem
But I have build ffmpeg for armv7, not arm64~

**Comment by kewlbear** [comment]
`inflate` returned -3 which is defined as `Z_DATA_ERROR` according to following URL.

http://zlib.net/manual.html#Constants

So I think the `png` file is corrupt or you are making some kind of mistake handling it.

HTH

**Comment by kangle1208** [comment]
Oh~The probleam has been fixed~
The reason is:
When the iOS project is build, the PNG file in the iOS project is changed by XCODE
If change the PNG file Suffix，for example：change logo.png to logo.pic
Then the PNG file will be decode succeed！
:-) Thank you for your reply, and happy every day !

**Comment by kewlbear** [comment]
Glad I could help.

**Comment by starjiang** [comment]
@kangle1208 i fix the same issue use your method,thanks

**Comment by kangle1208** [comment]
@starjiang
哇，美女程序员哎❤️
其实还有个方法，在XCode里面设置PNG图片的类型为data，也可以解决这个问题:-)
