### ISSUE TITLE
ffmpeg-3.3 build for arm64 failed

### ISSUE THREAD

**Issue by tubzby** [kewlbear/FFmpeg-iOS-build-script#98]
If I close neon support with --disable-neon, it's ok.

Here's the output:

> <instantiation>:1:14: error: invalid operand for instruction
smull v7.4S, ., v0.H[1]
             ^
<instantiation>:11:9: note: while in macro instantiation
        idct_col4_top v24 v25 v26 v27 14 
        ^
/var/folders/dq/2pz_pzg92tv54w4v5b0g9kjm0000gn/T/simple_idct_neon-02b625.s:234:1: note: while in macro instantiation
declare_idct_col4_neon 1 4H
^
<instantiation>:2:23: error: invalid operand for instruction
        smull v16.4S, ., v0.H[5]
                      ^
<instantiation>:11:9: note: while in macro instantiation
        idct_col4_top v24 v25 v26 v27 14 
        ^
/var/folders/dq/2pz_pzg92tv54w4v5b0g9kjm0000gn/T/simple_idct_neon-02b625.s:234:1: note: while in macro instantiation
declare_idct_col4_neon 1 4H

**Comment by kewlbear** [comment]
The new "configure" script does not use "gas-preprocessor.pl" for some reason. So I've updated my script to force it. Please update my script and try again. Thanks for reporting!

**Comment by tubzby** [comment]
it's ok now!
thanks.
