### ISSUE TITLE
FFmpeg commands

### ISSUE THREAD

**Issue by martisan** [kewlbear/FFmpeg-iOS-build-script#99]
Good day.

Thank you for the amazing build-script.
I just have a quick question.

I'm capturing a series of images that I want to convert to a video.
How would I execute the following FFmpeg command on a device:

```bash
ffmpeg -y -r 25 -i %d.jpg -preset ultrafast -start_number 1 -an -pix_fmt yuv420p -vcodec mjpeg -f mov -y out.mov
```

**Comment by kewlbear** [comment]
You can study `ffmpeg.c` and related files to find out how to code. The codes are not simple though.

**Comment by popctrl** [comment]
Kewlbear, does that mean this library won't give access to the ffmpeg.c functionalities? I have a similar case where all I need to do is run `ffmpeg -i input.flac -o output.wav`

**Comment by kewlbear** [comment]
@popctrl  `ffmpeg` program uses `FFmpeg` libraries to implement its functionalities. In your case you just need to study transcoding example.

**Comment by popctrl** [comment]
@kewlbear Thanks, that's what I did and was able to figure it out.
